// Generated by `yarn generate-listeners` (scripts/scripts.v2/ListenerManifestGenerator.ts).
// Do not edit: add a listener and its `<Listener>Factory`, then regenerate.

import type { ListenerManifest } from '#api/core/libs/eventEmitter/ListenerManifest.js';
import { DeleteSegmentationsOnFileDeleted } from './listeners/DeleteSegmentationsOnFileDeleted.js';
import { DeleteSegmentationsOnFileDeletedFactory } from './factories/DeleteSegmentationsOnFileDeletedFactory.js';
import { QueueSegmentationsOnFeatureEnabled } from './listeners/QueueSegmentationsOnFeatureEnabled.js';
import { QueueSegmentationsOnFeatureEnabledFactory } from './factories/QueueSegmentationsOnFeatureEnabledFactory.js';
import { SegmentOnFileCreated } from './listeners/SegmentOnFileCreated.js';
import { SegmentOnFileCreatedFactory } from './factories/SegmentOnFileCreatedFactory.js';

const listeners: ListenerManifest = [
  {
    listener: DeleteSegmentationsOnFileDeleted,
    factory: () => DeleteSegmentationsOnFileDeletedFactory.default(),
  },
  {
    listener: QueueSegmentationsOnFeatureEnabled,
    factory: () => QueueSegmentationsOnFeatureEnabledFactory.default(),
  },
  { listener: SegmentOnFileCreated, factory: () => SegmentOnFileCreatedFactory.default() },
];

export { listeners };
