export const SET_UPLOADS = 'SET_UPLOADS';
export const SET_THESAURIS_UPLOADS = 'SET_THESAURIS_UPLOADS';
export const SET_TEMPLATES_UPLOADS = 'SET_TEMPLATES_UPLOADS';
export const NEW_UPLOAD_DOCUMENT = 'NEW_UPLOAD_DOCUMENT';
