"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.CANCEL_RANGED_CONNECTION = exports.CREATING_RANGED_CONNECTION = exports.CREATING_CONNECTION = exports.SEARCHING_CONNECTIONS = exports.CLOSE_CONNECTION_PANEL = exports.OPEN_CONNECTION_PANEL = exports.CONNECTION_CREATED = exports.SET_TARGET_DOCUMENT = exports.SET_RELATION_TYPE = void 0;const SET_RELATION_TYPE = 'SET_RELATION_TYPE';exports.SET_RELATION_TYPE = SET_RELATION_TYPE;
const SET_TARGET_DOCUMENT = 'SET_TARGET_DOCUMENT';exports.SET_TARGET_DOCUMENT = SET_TARGET_DOCUMENT;
const CONNECTION_CREATED = 'CONNECTION_CREATED';
//UI
exports.CONNECTION_CREATED = CONNECTION_CREATED;const OPEN_CONNECTION_PANEL = 'OPEN_CONNECTION_PANEL';exports.OPEN_CONNECTION_PANEL = OPEN_CONNECTION_PANEL;
const CLOSE_CONNECTION_PANEL = 'CLOSE_CONNECTION_PANEL';exports.CLOSE_CONNECTION_PANEL = CLOSE_CONNECTION_PANEL;
const SEARCHING_CONNECTIONS = 'SEARCHING_CONNECTIONS';exports.SEARCHING_CONNECTIONS = SEARCHING_CONNECTIONS;
const CREATING_CONNECTION = 'CREATING_CONNECTION';exports.CREATING_CONNECTION = CREATING_CONNECTION;
const CREATING_RANGED_CONNECTION = 'CREATING_RANGED_CONNECTION';exports.CREATING_RANGED_CONNECTION = CREATING_RANGED_CONNECTION;
const CANCEL_RANGED_CONNECTION = 'CANCEL_RANGED_CONNECTION';exports.CANCEL_RANGED_CONNECTION = CANCEL_RANGED_CONNECTION;