import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowLeft,
  faArrowRight,
  faAngleLeft,
  faAngleRight,
  faChevronLeft,
  faChevronRight,
  faQuoteLeft,
  faQuoteRight,
  faBars,
  faCoffee,
  faTimes,
  faTh,
  faPowerOff,
  faCog,
  faCloudUploadAlt,
  faPlay,
  faFile,
  faFilePdf,
  faPencilAlt,
  faTrashAlt,
  faSave,
  faUpload,
  faPaperclip,
  faLink,
  faSpinner,
  faCheck,
  faCaretUp,
  faCaretDown,
  faExchangeAlt,
  faSync,
  faSearch,
  faFont,
  faSitemap,
  faInfoCircle,
  faCircle,
  faTimesCircle,
  faQuestionCircle,
  faLightbulb,
  faClock,
  faExclamationTriangle,
  faPaperPlane,
  faMapMarker,
  faTerminal,
  faPlus,
  faUndo,
  faHome,
  faEnvelope,
  faLanguage,
  faBook,
  faLock,
  faCalendar,
  faClone,
  faSort,
  faList,
  faCubes,
  faCalculator,
  faSortAlphaDown,
  faGavel,
  faChartBar,
  faParagraph
} from '@fortawesome/free-solid-svg-icons';

import {
  faSquare
} from '@fortawesome/free-regular-svg-icons';

const icons = {
  faArrowLeft,
  faArrowRight,
  faAngleLeft,
  faAngleRight,
  faChevronLeft,
  faChevronRight,
  faQuoteLeft,
  faQuoteRight,
  faBars,
  faCoffee,
  faTimes,
  faTh,
  faPowerOff,
  faCog,
  faCloudUploadAlt,
  faPlay,
  faFile,
  faFilePdf,
  faPencilAlt,
  faTrashAlt,
  faSave,
  faUpload,
  faPaperclip,
  faLink,
  faSpinner,
  faCheck,
  faSquare,
  faCaretUp,
  faCaretDown,
  faExchangeAlt,
  faSync,
  faSearch,
  faFont,
  faSitemap,
  faInfoCircle,
  faCircle,
  faTimesCircle,
  faQuestionCircle,
  faLightbulb,
  faClock,
  faExclamationTriangle,
  faPaperPlane,
  faMapMarker,
  faTerminal,
  faPlus,
  faUndo,
  faHome,
  faEnvelope,
  faLanguage,
  faBook,
  faLock,
  faCalendar,
  faClone,
  faSort,
  faList,
  faCubes,
  faCalculator,
  faSortAlphaDown,
  faGavel,
  faChartBar,
  faParagraph
};

export const loadIcons = () => {
  library.add(...Object.keys(icons).map(key => icons[key]));
};

export const iconNames = Object.keys(icons).map(key => icons[key].iconName);

