# Uwazi Development Container (not for production!)

# https://getfedora.org
FROM fedora:30

# Initially built by Michael Vorburger.ch at Google for Huridocs, later maintained by the Uwazi open source community
LABEL maintainer="Michael Vorburger.ch <vorburger@google.com>"

# Update base image (the public one is typically outdated and contains already patched security vulnerabilities)
RUN dnf update -y

# https://docs.mongodb.com/v3.4/tutorial/install-mongodb-on-red-hat/
COPY mongodb-org-3.4.repo /etc/yum.repos.d/mongodb-org-3.4.repo

# Install utility packages generally useful in any devshell
RUN dnf install -y git findutils less which \

# Install system packages specifically required by Uwazi
    libpng12-devel libpng-devel mongodb-org-shell mongodb-org-tools poppler

# Create ~uwazi and switch to it (without this, Node & Co. would get installed as root)
RUN useradd uwazi
USER uwazi

# Install Node.JS
# Due to https://github.com/nodesource/distributions/issues/842, NOT https://github.com/nodesource/distributions/#rpminstall
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
RUN source $HOME/.nvm/nvm.sh  \
 && nvm install 8.11 \
 && node --version

# Install Yarn
# https://yarnpkg.com/en/docs/install
# use simple installation script method instead of OS package,
# because package manager dependencies are a mess if Node is installed by NVM instead of package (above)
RUN source $HOME/.nvm/nvm.sh \
 && curl -o- -L https://yarnpkg.com/install.sh | bash \
 && $HOME/.yarn/bin/yarn --version

RUN mkdir /home/uwazi/git
WORKDIR /home/uwazi/git
# TODO rm git clone and replace with mounting from host
RUN git clone https://github.com/huridocs/uwazi.git . \
 && source $HOME/.nvm/nvm.sh \
 && $HOME/.yarn/bin/yarn install

# NB: Can't run "yarn test" during BUILD, because it requires MongoDB.

# NB Do not run yarn blank-state & hot here (in ENTRYPOINT), but let the developer do this manually
ENTRYPOINT bash -c echo "TODO" && sleep infinity
