export default {
  checkbox: 'check',
  numeric: 'calculator',
  relationship: 'link',
  relationshipfilter: 'filter',
  select: 'sort',
  multiselect: 'list',
  date: 'calendar',
  text: 'font',
  markdown: 'file',
  nested: 'cubes',
  multidate: 'calendar',
  multidaterange: 'calendar',
  daterange: 'calendar',
  multimedia: 'image',
  geolocation: 'map-marker',
};
