import activitylogMiddleware from './activitylog/activitylogMiddleware';
import CSRFMiddleware from './auth/CSRFMiddleware';
import languageMiddleware from './utils/languageMiddleware';
import { setupApiSockets } from './socketio/setupSockets';
import { documentRoutes } from './documents/routes';
import { searchRoutes } from './search.v2/routes';
import { ocrRoutes } from './files/ocrRoutes';
import { permissionRoutes } from './permissions/routes';
import { suggestionsRoutes } from './suggestions/routes';
import { extractorsRoutes } from './suggestions/extractorsRoutes';
import { PreserveRoutes } from './preserve/routes';
import auth2fa from './auth2fa/routes';
import relationships from './relationships/routes';
import relationshipsV2 from './relationships.v2/routes/routes';
import activitylog from './activitylog/routes';
import users from './users/routes';
import templates from './templates/routes';
import searchDeprecatedRoutes from './search/deprecatedRoutes';
import search from './search/routes';
import topicclassification from './topicclassification/routes';
import thesauri from './thesauri/routes';
import relationtypes from './relationtypes/routes';
import documents from './documents/deprecatedRoutes';
import contact from './contact/routes';
import entities from './entities/routes';
import pages from './pages/routes';
import filesJSRoutes from './files/jsRoutes.js';
import files from './files/routes';
import filesExportRouter from './files/exportRoutes';
import settings from './settings/routes';
import i18n from './i18n/routes';
import sync from './sync/routes';
import tasks from './tasks/routes';
import usergroups from './usergroups/routes';
import stats from './stats/routes';

export default (app, server) => {
  app.use(CSRFMiddleware);
  app.use(languageMiddleware);
  app.use(activitylogMiddleware);
  setupApiSockets(server, app);
  documentRoutes(app);
  searchRoutes(app);
  ocrRoutes(app);
  permissionRoutes(app);
  suggestionsRoutes(app);
  extractorsRoutes(app);
  PreserveRoutes(app);
  auth2fa(app);
  relationships(app);
  relationshipsV2(app);
  activitylog(app);
  users(app);
  templates(app);
  searchDeprecatedRoutes(app);
  search(app);
  topicclassification(app);
  thesauri(app);
  relationtypes(app);
  documents(app);
  contact(app);
  entities(app);
  pages(app);
  filesJSRoutes(app);
  files(app);
  filesExportRouter(app);
  settings(app);
  i18n(app);
  sync(app);
  tasks(app);
  usergroups(app);
  stats(app);
};
