// Generated by `yarn generate-listeners` (scripts/scripts.v2/ListenerManifestGenerator.ts).
// Do not edit: add a listener and its `<Listener>Factory`, then regenerate.

import type { ListenerManifest } from '#api/core/libs/eventEmitter/ListenerManifest.js';
import { AddLanguagePagesListener } from './pages.v2/infrastructure/listeners/AddLanguagePagesListener.js';
import { AddLanguagePagesListenerFactory } from './pages.v2/infrastructure/factories/AddLanguagePagesListenerFactory.js';
import { BroadcastSettingsChanged } from './core/infrastructure/listeners/BroadcastSettingsChanged.js';
import { BroadcastSettingsChangedFactory } from './core/infrastructure/factories/BroadcastSettingsChangedFactory.js';
import { DeleteLanguagePagesListener } from './pages.v2/infrastructure/listeners/DeleteLanguagePagesListener.js';
import { DeleteLanguagePagesListenerFactory } from './pages.v2/infrastructure/factories/DeleteLanguagePagesListenerFactory.js';
import { ProcessRelationshipAfterEntityUpdatedListener } from './core/infrastructure/listeners/ProcessRelationshipAfterEntityUpdatedListener.js';
import { ProcessRelationshipAfterEntityUpdatedListenerFactory } from './core/infrastructure/factories/ProcessRelationshipAfterEntityUpdatedListenerFactory.js';

const listeners: ListenerManifest = [
  { listener: AddLanguagePagesListener, factory: () => AddLanguagePagesListenerFactory.default() },
  { listener: BroadcastSettingsChanged, factory: () => BroadcastSettingsChangedFactory.default() },
  {
    listener: DeleteLanguagePagesListener,
    factory: () => DeleteLanguagePagesListenerFactory.default(),
  },
  {
    listener: ProcessRelationshipAfterEntityUpdatedListener,
    factory: () => ProcessRelationshipAfterEntityUpdatedListenerFactory.default(),
  },
];

export { listeners };
