"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.SEARCHING_RELATIONSHIPS = exports.CLOSE_RELATIONSHIPS_PANEL = exports.OPEN_RELATIONSHIPS_PANEL = exports.SAVED_RELATIONSHIPS = exports.SAVING_RELATIONSHIPS = exports.EDIT_RELATIONSHIPS = exports.MOVE_RELATIONSHIPS_ENTITY = exports.TOGGLE_MOVE_RELATIONSHIPS_ENTITY = exports.TOGGLE_REMOVE_RELATIONSHIPS_ENTITY = exports.ADD_RELATIONSHIPS_ENTITY = exports.SET_RELATIONSHIPS_ADD_TO_DATA = exports.TOGGLE_REMOVE_RELATIONSHIPS_RIGHT_GROUP = exports.TOGGLE_REMOVE_RELATIONSHIPS_LEFT = exports.UPDATE_RELATIONSHIPS_RIGHT_TYPE = exports.UPDATE_RELATIONSHIPS_LEFT_TYPE = exports.ADD_RELATIONSHIPS_HUB = exports.PARSE_RELATIONSHIPS_RESULTS = void 0;const PARSE_RELATIONSHIPS_RESULTS = 'PARSE_RELATIONSHIPS_RESULTS';exports.PARSE_RELATIONSHIPS_RESULTS = PARSE_RELATIONSHIPS_RESULTS;
const ADD_RELATIONSHIPS_HUB = 'ADD_RELATIONSHIPS_HUB';exports.ADD_RELATIONSHIPS_HUB = ADD_RELATIONSHIPS_HUB;
const UPDATE_RELATIONSHIPS_LEFT_TYPE = 'UPDATE_RELATIONSHIPS_LEFT_TYPE';exports.UPDATE_RELATIONSHIPS_LEFT_TYPE = UPDATE_RELATIONSHIPS_LEFT_TYPE;
const UPDATE_RELATIONSHIPS_RIGHT_TYPE = 'UPDATE_RELATIONSHIPS_RIGHT_TYPE';exports.UPDATE_RELATIONSHIPS_RIGHT_TYPE = UPDATE_RELATIONSHIPS_RIGHT_TYPE;
const TOGGLE_REMOVE_RELATIONSHIPS_LEFT = 'TOGGLE_REMOVE_RELATIONSHIPS_LEFT';exports.TOGGLE_REMOVE_RELATIONSHIPS_LEFT = TOGGLE_REMOVE_RELATIONSHIPS_LEFT;
const TOGGLE_REMOVE_RELATIONSHIPS_RIGHT_GROUP = 'TOGGLE_REMOVE_RELATIONSHIPS_RIGHT_GROUP';exports.TOGGLE_REMOVE_RELATIONSHIPS_RIGHT_GROUP = TOGGLE_REMOVE_RELATIONSHIPS_RIGHT_GROUP;
const SET_RELATIONSHIPS_ADD_TO_DATA = 'EDIT_RELATIONSHIPS_GROUP';exports.SET_RELATIONSHIPS_ADD_TO_DATA = SET_RELATIONSHIPS_ADD_TO_DATA;
const ADD_RELATIONSHIPS_ENTITY = 'ADD_RELATIONSHIPS_ENTITY';exports.ADD_RELATIONSHIPS_ENTITY = ADD_RELATIONSHIPS_ENTITY;
const TOGGLE_REMOVE_RELATIONSHIPS_ENTITY = 'TOGGLE_REMOVE_RELATIONSHIPS_ENTITY';exports.TOGGLE_REMOVE_RELATIONSHIPS_ENTITY = TOGGLE_REMOVE_RELATIONSHIPS_ENTITY;
const TOGGLE_MOVE_RELATIONSHIPS_ENTITY = 'TOGGLE_MOVE_RELATIONSHIPS_ENTITY';exports.TOGGLE_MOVE_RELATIONSHIPS_ENTITY = TOGGLE_MOVE_RELATIONSHIPS_ENTITY;
const MOVE_RELATIONSHIPS_ENTITY = 'MOVE_RELATIONSHIPS_ENTITY';exports.MOVE_RELATIONSHIPS_ENTITY = MOVE_RELATIONSHIPS_ENTITY;

const EDIT_RELATIONSHIPS = 'EDIT_RELATIONSHIPS';exports.EDIT_RELATIONSHIPS = EDIT_RELATIONSHIPS;
const SAVING_RELATIONSHIPS = 'SAVING_RELATIONSHIPS';exports.SAVING_RELATIONSHIPS = SAVING_RELATIONSHIPS;
const SAVED_RELATIONSHIPS = 'SAVED_RELATIONSHIPS';

//UI
exports.SAVED_RELATIONSHIPS = SAVED_RELATIONSHIPS;const OPEN_RELATIONSHIPS_PANEL = 'OPEN_RELATIONSHIPS_PANEL';exports.OPEN_RELATIONSHIPS_PANEL = OPEN_RELATIONSHIPS_PANEL;
const CLOSE_RELATIONSHIPS_PANEL = 'CLOSE_RELATIONSHIPS_PANEL';exports.CLOSE_RELATIONSHIPS_PANEL = CLOSE_RELATIONSHIPS_PANEL;
const SEARCHING_RELATIONSHIPS = 'SEARCHING_RELATIONSHIPS';exports.SEARCHING_RELATIONSHIPS = SEARCHING_RELATIONSHIPS;