"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.SAVING_TEMPLATE = exports.HIDE_REMOVE_PROPERTY_CONFIRM = exports.SHOW_REMOVE_PROPERTY_CONFIRM = exports.SET_THESAURIS = exports.EDIT_PROPERTY = exports.RESET_TEMPLATE = exports.SET_TEMPLATE = exports.DELETE_TEMPLATE = exports.TEMPLATE_SAVED = exports.SET_TEMPLATES = exports.SELECT_PROPERTY = exports.UPDATE_TEMPLATE = exports.UPDATE_PROPERTY = exports.REORDER_PROPERTY = exports.REMOVE_PROPERTY = exports.ADD_PLACEHOLDER = exports.ADD_PROPERTY = void 0; //DATA
const ADD_PROPERTY = 'ADD_PROPERTY';exports.ADD_PROPERTY = ADD_PROPERTY;
const ADD_PLACEHOLDER = 'ADD_PLACEHOLDER';exports.ADD_PLACEHOLDER = ADD_PLACEHOLDER;
const REMOVE_PROPERTY = 'REMOVE_PROPERTY';exports.REMOVE_PROPERTY = REMOVE_PROPERTY;
const REORDER_PROPERTY = 'REORDER_PROPERTY';exports.REORDER_PROPERTY = REORDER_PROPERTY;
const UPDATE_PROPERTY = 'UPDATE_PROPERTY';exports.UPDATE_PROPERTY = UPDATE_PROPERTY;
const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE';exports.UPDATE_TEMPLATE = UPDATE_TEMPLATE;
const SELECT_PROPERTY = 'SELECT_PROPERTY';exports.SELECT_PROPERTY = SELECT_PROPERTY;
const SET_TEMPLATES = 'SET_TEMPLATES';exports.SET_TEMPLATES = SET_TEMPLATES;
const TEMPLATE_SAVED = 'TEMPLATE_SAVED';exports.TEMPLATE_SAVED = TEMPLATE_SAVED;
const DELETE_TEMPLATE = 'DELETE_TEMPLATE';exports.DELETE_TEMPLATE = DELETE_TEMPLATE;
const SET_TEMPLATE = 'SET_TEMPLATE';exports.SET_TEMPLATE = SET_TEMPLATE;
const RESET_TEMPLATE = 'RESET_TEMPLATE';

//UI
exports.RESET_TEMPLATE = RESET_TEMPLATE;const EDIT_PROPERTY = 'EDIT_PROPERTY';exports.EDIT_PROPERTY = EDIT_PROPERTY;
const SET_THESAURIS = 'SET_THESAURIS';exports.SET_THESAURIS = SET_THESAURIS;
const SHOW_REMOVE_PROPERTY_CONFIRM = 'SHOW_REMOVE_PROPERTY_CONFIRM';exports.SHOW_REMOVE_PROPERTY_CONFIRM = SHOW_REMOVE_PROPERTY_CONFIRM;
const HIDE_REMOVE_PROPERTY_CONFIRM = 'HIDE_REMOVE_PROPERTY_CONFIRM';exports.HIDE_REMOVE_PROPERTY_CONFIRM = HIDE_REMOVE_PROPERTY_CONFIRM;
const SAVING_TEMPLATE = 'SAVING_TEMPLATE';exports.SAVING_TEMPLATE = SAVING_TEMPLATE;