export const PARSE_RELATIONSHIPS_RESULTS = 'PARSE_RELATIONSHIPS_RESULTS';
export const ADD_RELATIONSHIPS_HUB = 'ADD_RELATIONSHIPS_HUB';
export const UPDATE_RELATIONSHIPS_LEFT_TYPE = 'UPDATE_RELATIONSHIPS_LEFT_TYPE';
export const UPDATE_RELATIONSHIPS_RIGHT_TYPE = 'UPDATE_RELATIONSHIPS_RIGHT_TYPE';
export const TOGGLE_REMOVE_RELATIONSHIPS_LEFT = 'TOGGLE_REMOVE_RELATIONSHIPS_LEFT';
export const TOGGLE_REMOVE_RELATIONSHIPS_RIGHT_GROUP = 'TOGGLE_REMOVE_RELATIONSHIPS_RIGHT_GROUP';
export const EDIT_RELATIONSHIPS_GROUP = 'EDIT_RELATIONSHIPS_GROUP';
export const ADD_RELATIONSHIPS_ENTITY = 'ADD_RELATIONSHIPS_ENTITY';
export const TOGGLE_REMOVE_RELATIONSHIPS_ENTITY = 'TOGGLE_REMOVE_RELATIONSHIPS_ENTITY';

export const SAVING_RELATIONSHIPS = 'SAVING_RELATIONSHIPS';
export const SAVED_RELATIONSHIPS = 'SAVED_RELATIONSHIPS';

//UI
export const OPEN_RELATIONSHIPS_PANEL = 'OPEN_RELATIONSHIPS_PANEL';
export const CLOSE_RELATIONSHIPS_PANEL = 'CLOSE_RELATIONSHIPS_PANEL';
export const SEARCHING_RELATIONSHIPS = 'SEARCHING_RELATIONSHIPS';
