/*
This migration is meant to be repeatable.
After copy pasting:
  - update migration number
  - change the contents of systemKeys to the new keyset
  - change the tests, if necessary
*/

async function insertSystemKeys(db, newKeys) {
  const translations = await db.collection('translations').find().toArray();
  const locales = translations.map(tr => tr.locale);

  const locToSystemContext = {};
  translations.forEach(tr => {
    locToSystemContext[tr.locale] = tr.contexts.find(c => c.id === 'System');
  });
  const locToKeys = {};
  Object.entries(locToSystemContext).forEach(([loc, context]) => {
    locToKeys[loc] = new Set(context.values.map(v => v.key));
  });

  newKeys.forEach(row => {
    const { key, value: optionalValue } = row;

    locales.forEach(loc => {
      if (!locToKeys[loc].has(key)) {
        const newValue = optionalValue || key;
        locToSystemContext[loc].values.push({ key, value: newValue });
        locToKeys[loc].add(key);
      }
    });
  });

  await Promise.all(
    translations.map(tr => db.collection('translations').replaceOne({ _id: tr._id }, tr))
  );
}

export default {
  delta: 137,

  reindex: false,

  name: 'add_system_key_translations',

  description: 'Adding missing translations for system keys.',

  async up(db) {
    process.stdout.write(`${this.name}...\r\n`);
    const systemKeys = [
      { key: 'Copy to clipboard' },
      { key: 'Account updated' },
      { key: 'General Information' },
      { key: 'User Role' },
      { key: 'Change Password' },
      { key: 'New Password' },
      { key: 'Passwords do not match' },
      { key: 'Confirm New Passowrd' },
      { key: 'Two-Factor Authentication' },
      { key: 'Activated' },
      { key: "Your account's security is enhanced with two-factor authentication." },
      { key: 'Two-Factor Authentication' },
      { key: 'Enable' },
      { key: 'You should activate this feature for enhanced account security.' },
      { key: 'Two-Factor Authentication' },
      { key: '2FA Enabled' },
      { key: 'Using Authenticator' },
      { key: 'Download a third-party authenticator app from your mobile store.' },
      {
        key: 'Add an account to the app by scanning the provided QR code with your mobile device or by inserting the provided key.',
      },
      {
        key: "Instructions on how to achieve this will vary according to the app used, please refer to the app's documentation.",
      },
      { key: 'QR Code' },
      { key: 'Secret keys' },
      { key: 'You can also enter this secret key into your Authenticator app.' },
      { key: "*please keep this key secret and don't share it." },
      { key: 'Enter the 6-digit verification code generated by your Authenticator app' },
      { key: 'The token does not validate against the secret key' },
    ];
    await insertSystemKeys(db, systemKeys);
  },
};
