"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.UPDATE_DOCUMENT_FILE = exports.ATTACHMENT_RENAMED = exports.ATTACHMENT_DELETED = exports.ATTACHMENT_COMPLETE = exports.ATTACHMENT_PROGRESS = exports.START_UPLOAD_ATTACHMENT = void 0;const START_UPLOAD_ATTACHMENT = 'START_UPLOAD_ATTACHMENT';exports.START_UPLOAD_ATTACHMENT = START_UPLOAD_ATTACHMENT;
const ATTACHMENT_PROGRESS = 'ATTACHMENT_PROGRESS';exports.ATTACHMENT_PROGRESS = ATTACHMENT_PROGRESS;
const ATTACHMENT_COMPLETE = 'ATTACHMENT_COMPLETE';exports.ATTACHMENT_COMPLETE = ATTACHMENT_COMPLETE;
const ATTACHMENT_DELETED = 'ATTACHMENT_DELETED';exports.ATTACHMENT_DELETED = ATTACHMENT_DELETED;
const ATTACHMENT_RENAMED = 'ATTACHMENT_RENAMED';exports.ATTACHMENT_RENAMED = ATTACHMENT_RENAMED;
const UPDATE_DOCUMENT_FILE = 'UPDATE_DOCUMENT_FILE';exports.UPDATE_DOCUMENT_FILE = UPDATE_DOCUMENT_FILE;