import { EntitySchema } from 'shared/types/entityType';
import { ProcessingContext } from '../types';

export const rawEntity: EntitySchema = {
  _id: '68dded72c9474e23bb5e9254',
  language: 'en',
  mongoLanguage: 'en',
  sharedId: '36l0vr92qce',
  title: 'Emergency Incident Report - Downtown Traffic Accident',
  template: '68ddecdbc9474e23bb5e914b',
  published: false,
  creationDate: 1759374706197, // Oct 2, 2025 (seconds)
  editDate: 1760366924144, // Oct 13, 2025 (seconds)
  metadata: {
    simple_text: [
      {
        value: 'Emergency incident report from downtown area',
      },
    ],
    markdown_syntax: [
      {
        value:
          '# Emergency Incident Report\n## Incident Details\n### Location: Downtown Area\n\n**Incident Type:** Traffic Accident\n**Time:** 14:30\n**Status:** Under Investigation',
      },
    ],
    single_date: [
      {
        value: 1759363200,
      },
    ],
    location_of_interest: [
      {
        value: {
          lat: 46.3964365565104,
          lon: 3.6694335937500004,
          label: '',
        },
      },
    ],
    multiple_dates: [
      {
        value: 1759276800,
      },
      {
        value: 1759363200,
      },
      {
        value: 1759449600,
      },
    ],
    date_range: [
      {
        value: {
          from: 1759276800,
          to: 1761955199,
        },
      },
    ],
    multiple_date_ranges: [
      {
        value: {
          from: 1759276800,
          to: 1759449599,
        },
      },
      {
        value: {
          from: 1759363200,
          to: 1759535999,
        },
      },
    ],
    status_selection: [
      {
        value: '9e22a1af-75d7-49a2-b9d8-9ec77939b630',
        label: 'Again',
      },
    ],
    category_tags: [
      {
        value: '765ab6ca-56a1-4948-9dc9-17fc0aa30843',
        label: 'Acknowledging',
      },
      {
        value: '9e22a1af-75d7-49a2-b9d8-9ec77939b630',
        label: 'Again',
      },
      {
        value: '8c418311-1244-4777-800a-65729b8c17a8',
        label: 'verb2',
        parent: {
          value: '68979984-35ac-4b98-abf9-28eac857749c',
          label: 'grouped',
        },
      },
      {
        value: 'e1b9944b-43ef-4989-837b-b3df79284b00',
        label: 'verb1',
        parent: {
          value: '68979984-35ac-4b98-abf9-28eac857749c',
          label: 'grouped',
        },
      },
    ],
    related_people: [
      {
        value: 'xjku67dv7b',
        label: 'Maria Rodriguez - Witness',
        icon: {
          _id: 'ECU',
          label: 'Ecuador',
          type: 'Flags',
        },
        type: 'entity',
        inheritedValue: [
          {
            value: '9e22a1af-75d7-49a2-b9d8-9ec77939b630',
            label: 'Again',
          },
          {
            value: '765ab6ca-56a1-4948-9dc9-17fc0aa30843',
            label: 'Acknowledging',
          },
        ],
        inheritedType: 'multiselect',
      },
      {
        value: '4oklamamet',
        label: 'John Smith - Reporter',
        icon: '',
        type: 'entity',
        inheritedValue: [
          {
            value: '6c744926-bf38-4f98-8c74-cf6b7280863c',
            label: 'Expressing',
          },
          {
            value: '8c418311-1244-4777-800a-65729b8c17a8',
            label: 'verb2',
            parent: {
              value: '68979984-35ac-4b98-abf9-28eac857749c',
              label: 'grouped',
            },
          },
        ],
        inheritedType: 'multiselect',
      },
    ],
    nearby_incidents: [
      {
        value: 'xjku67dv7b',
        label: 'Traffic Accident - Main Street',
        icon: {
          _id: 'ECU',
          label: 'Ecuador',
          type: 'Flags',
        },
        type: 'entity',
      },
      {
        value: '4oklamamet',
        label: 'Fire Incident - Downtown',
        icon: '',
        type: 'entity',
      },
    ],
    external_link: [
      {
        value: {
          label: 'Police Report',
          url: 'https://police.gov/reports/incident-2024-001',
        },
      },
    ],
    selected_image: [
      {
        value: '/api/files/17593747059321ygqk22fdos.png',
      },
    ],
    preview_document: [
      {
        value: '',
      },
    ],
    video_of_event: [
      {
        value:
          '(/api/files/1759374705932xi5rx0mumef.mp4, {"timelinks":{"00:20:15":"control","01:30:45":"Test timelink"}})',
      },
    ],
    incident_location: [
      {
        value: {
          lat: 44.33301685687683,
          lon: 5.998535156250001,
          label: '',
        },
      },
    ],
    secondary_location: [
      {
        value: {
          lat: 62.58069554111894,
          lon: 15.468750000000002,
          label: '',
        },
      },
    ],
    location_relationships: [
      {
        value: 'xjku67dv7b',
        label: 'Witness Location - Maria Rodriguez',
        icon: {
          _id: 'ECU',
          label: 'Ecuador',
          type: 'Flags',
        },
        type: 'entity',
        inheritedValue: [
          {
            value: {
              lat: 43.80157978110818,
              lon: 7.492675781250001,
              label: 'Witness Home Address',
            },
          },
        ],
        inheritedType: 'geolocation',
      },
      {
        value: '4oklamamet',
        label: 'Reporter Location - John Smith',
        icon: '',
        type: 'entity',
        inheritedValue: [],
        inheritedType: 'geolocation',
      },
    ],
    document_id: [
      {
        value: 'EVT-2024-001',
      },
    ],
    hierarchical_relationships: [
      {
        value: '6qdshinfobf',
        label: 'Emergency Response Team',
        icon: '',
        type: 'entity',
        inheritedValue: [
          {
            value: '7jdr88mnow6',
            label: 'First Responders',
            icon: '',
            type: 'entity',
            inheritedValue: [
              {
                value: 'xjku67dv7b',
                label: 'Police Officer - Maria Rodriguez',
                icon: {
                  _id: 'ECU',
                  label: 'Ecuador',
                  type: 'Flags',
                },
                type: 'entity',
                inheritedValue: [
                  {
                    value: '9e22a1af-75d7-49a2-b9d8-9ec77939b630',
                    label: 'Again',
                  },
                  {
                    value: '765ab6ca-56a1-4948-9dc9-17fc0aa30843',
                    label: 'Acknowledging',
                  },
                ],
                inheritedType: 'multiselect',
              },
            ],
            inheritedType: 'relationship',
          },
        ],
        inheritedType: 'relationship',
      },
    ],
  },
  user: '58ada34d299e82674854510f',
  permissions: [
    {
      refId: '58ada34d299e82674854510f',
      type: 'user',
      level: 'write',
    },
  ],
  obsoleteMetadata: [],
  __v: 11,
};

export const processingContext: ProcessingContext = {
  includeTemplate: true,
  includeMetadata: true,
  includeRelationships: false,
  includeFiles: false,
  includeNavigation: false,
  includePermissions: true,
  combineGeolocation: true,
  onlyForCards: true,
  formatDates: true,
  dateFormat: 'LLL d, yyyy',
  translateLabels: true,
  language: 'en',
  translations: [
    {
      locale: 'en',
      contexts: [
        {
          id: '5bfbb1a0471dd0fc16ada146',
          label: 'Event Report',
          type: 'Entity',
          values: {
            'Event Report': 'Event Report EN',
            Date: 'Date EN',
            Title: 'Title EN',
            Multiselect: 'Multiselect EN',
            Markdown: 'Markdown EN',
            'Multiselect from text': 'Multiselect from text EN',
            GeolocationD: 'GeolocationD EN',
          },
        },
        {
          id: '68d6ed4891b591b7432b276b',
          label: 'Verbs',
          type: 'Thesaurus',
          values: {
            Verbs: 'Verbs EN',
            Acknowledging: 'Acknowledging EN',
            Again: 'Again EN',
            Confirming: 'Confirming EN',
            Expressing: 'Expressing EN',
            grouped: 'grouped EN',
            verb1: 'verb1 EN',
            verb2: 'verb2 EN',
          },
        },
        {
          id: '68da997861bceda4fe0d6d25',
          label: 'TextDocument',
          type: 'Entity',
          values: {
            Numeric: 'Numeric EN',
            Markdown: 'Markdown EN',
            TextDocument: 'TextDocument EN',
            Title: 'Title EN',
            Multiselect: 'Multiselect EN',
          },
        },
        {
          id: '68da99b961bceda4fe0d6ddd',
          label: 'related from',
          values: {
            'related from': 'related from EN',
          },
        },
        {
          id: '68da99d961bceda4fe0d6e0f',
          label: 'related to',
          type: 'Relationship Type',
          values: {
            'related to': 'related to EN',
          },
        },
        {
          id: '68ddecdbc9474e23bb5e914b',
          label: 'Emergency Incident Report Template',
          type: 'Entity',
          values: {
            'Simple Text': 'Simple Text EN',
            'Markdown Syntax': 'Markdown Syntax EN',
            'Single Date': 'Single Date EN',
            'Multiple Dates': 'Multiple Dates EN',
            'Date Range': 'Date Range EN',
            'Status Selection': 'Status Selection EN',
            'Category Tags': 'Category Tags EN',
            'Related People': 'Related People EN',
            'External Link': 'External Link EN',
            'Selected Image': 'Selected Image EN',
            'Preview Document': 'Preview Document EN',
            'Video of Event': 'Video of Event EN',
            'Incident Location': 'Incident Location EN',
            'Document ID': 'Document ID EN',
            'Emergency Incident Report Template': 'Emergency Incident Report Template EN',
            Title: 'Title EN',
            'Multiple Date Ranges': 'Multiple Date Ranges EN',
            'Nearby Incidents': 'Nearby Incidents EN',
            'Secondary Location': 'Secondary Location EN',
            'Location Relationships': 'Location Relationships EN',
            'Location of Interest': 'Location of Interest EN',
            'Hierarchical Relationships': 'Hierarchical Relationships EN',
          },
        },
        {
          id: '68ec577980a3354966fb293c',
          label: 'middle',
          type: 'Entity',
          values: {
            middle: 'middle EN',
            Title: 'Title EN',
            'Relationship n-2': 'Relationship n-2 EN',
          },
        },
        {
          id: '68ec5bf780a3354966fb2c25',
          label: 'extra level',
          type: 'Entity',
          values: {
            'extra level': 'extra level EN',
            Title: 'Title EN',
            'Relationship n-1': 'Relationship n-1 EN',
          },
        },
      ],
    },
  ],
  templates: [
    {
      _id: '5bfbb1a0471dd0fc16ada146',
      name: 'Event Report',
      commonProperties: [
        {
          _id: '5bfbb1a0471dd0fc16ada148',
          label: 'Title',
          name: 'title',
          isCommonProperty: true,
          type: 'text',
          prioritySorting: false,
        },
        {
          _id: '5bfbb1a0471dd0fc16ada147',
          label: 'Date added',
          name: 'creationDate',
          isCommonProperty: true,
          type: 'date',
          prioritySorting: false,
        },
        {
          _id: '68da9640ea8d8c69971bf274',
          label: 'Date modified',
          name: 'editDate',
          type: 'date',
          isCommonProperty: true,
        },
      ],
      properties: [
        {
          content: '68d6ed4891b591b7432b276b',
          _id: '68d6f62891b591b7432b2b4b',
          type: 'multiselect',
          label: 'Multiselect',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'category_tags',
        },
        {
          _id: '68e5e0eb192fccdd1003624b',
          type: 'geolocation',
          label: 'GeolocationD',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'geolocationd_geolocation',
        },
      ],
      __v: 8,
      default: false,
      color: '#16bdca',
      entityViewPage: '',
    },
    {
      _id: '68da997861bceda4fe0d6d25',
      color: '#C03B22',
      properties: [
        {
          _id: '68da997861bceda4fe0d6d26',
          type: 'numeric',
          label: 'Numeric',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'numeric',
        },
        {
          _id: '68da997861bceda4fe0d6d27',
          type: 'markdown',
          label: 'Markdown',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'markdown_syntax',
        },
        {
          content: '68d6ed4891b591b7432b276b',
          _id: '68da999561bceda4fe0d6da6',
          type: 'multiselect',
          label: 'Multiselect',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'category_tags',
        },
      ],
      commonProperties: [
        {
          _id: '68da997861bceda4fe0d6d28',
          label: 'Title',
          name: 'title',
          type: 'text',
          isCommonProperty: true,
        },
        {
          _id: '68da997861bceda4fe0d6d29',
          label: 'Date added',
          name: 'creationDate',
          type: 'date',
          isCommonProperty: true,
        },
        {
          _id: '68da997861bceda4fe0d6d2a',
          label: 'Date modified',
          name: 'editDate',
          type: 'date',
          isCommonProperty: true,
        },
      ],
      entityViewPage: '',
      name: 'TextDocument',
      __v: 2,
      default: true,
    },
    {
      _id: '68ddecdbc9474e23bb5e914b',
      color: '#C03B22',
      properties: [
        {
          _id: '68ddecdbc9474e23bb5e914c',
          type: 'text',
          label: 'Simple Text',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'simple_text',
        },
        {
          _id: '68ddecdbc9474e23bb5e914d',
          type: 'markdown',
          label: 'Markdown Syntax',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'markdown_syntax',
        },
        {
          _id: '68ddecdbc9474e23bb5e914e',
          type: 'date',
          label: 'Single Date',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'single_date',
        },
        {
          _id: '68e5e13b192fccdd10036334',
          type: 'geolocation',
          label: 'Location of Interest',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'location_of_interest',
        },
        {
          _id: '68ddecdbc9474e23bb5e914f',
          type: 'multidate',
          label: 'Multiple Dates',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'multiple_dates',
        },
        {
          _id: '68ddecdbc9474e23bb5e9150',
          type: 'daterange',
          label: 'Date Range',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'date_range',
        },
        {
          _id: '68e56b29192fccdd10035c2a',
          type: 'multidaterange',
          label: 'Multiple Date Ranges',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'multiple_date_ranges',
        },
        {
          content: '68d6ed4891b591b7432b276b',
          _id: '68ddecdbc9474e23bb5e9151',
          type: 'select',
          label: 'Status Selection',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'status_selection',
        },
        {
          content: '68d6ed4891b591b7432b276b',
          _id: '68ddecdbc9474e23bb5e9152',
          type: 'multiselect',
          label: 'Category Tags',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'category_tags',
        },
        {
          content: '5bfbb1a0471dd0fc16ada146',
          _id: '68ddecdbc9474e23bb5e9153',
          type: 'relationship',
          label: 'Related People',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          relationType: '68da99b961bceda4fe0d6ddd',
          inherit: {
            property: '68d6f62891b591b7432b2b4b',
            type: 'multiselect',
          },
          generatedId: false,
          name: 'related_people',
        },
        {
          content: '5bfbb1a0471dd0fc16ada146',
          _id: '68e585e4192fccdd10035da9',
          type: 'relationship',
          label: 'Nearby Incidents',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          relationType: '68da99b961bceda4fe0d6ddd',
          generatedId: false,
          name: 'nearby_incidents',
        },
        {
          _id: '68ddecdbc9474e23bb5e9154',
          type: 'link',
          label: 'External Link',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'external_link',
        },
        {
          _id: '68ddecdbc9474e23bb5e9155',
          type: 'image',
          label: 'Selected Image',
          noLabel: false,
          required: false,
          showInCard: false,
          style: 'fill',
          generatedId: false,
          name: 'selected_image',
        },
        {
          _id: '68ddecdbc9474e23bb5e9156',
          type: 'preview',
          label: 'Preview Document',
          noLabel: false,
          required: false,
          showInCard: false,
          style: 'fill',
          generatedId: false,
          name: 'preview_document',
        },
        {
          _id: '68ddecdbc9474e23bb5e9157',
          type: 'media',
          label: 'Video of Event',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'video_of_event',
        },
        {
          _id: '68ddecdbc9474e23bb5e9158',
          type: 'geolocation',
          label: 'Incident Location',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'incident_location',
        },
        {
          _id: '68e5e0d9192fccdd100361d3',
          type: 'geolocation',
          label: 'Secondary Location',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'secondary_location',
        },
        {
          content: '5bfbb1a0471dd0fc16ada146',
          _id: '68e5e119192fccdd100362cb',
          type: 'relationship',
          label: 'Location Relationships',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          relationType: '68da99b961bceda4fe0d6ddd',
          inherit: {
            property: '68e5e0eb192fccdd1003624b',
            type: 'geolocation',
          },
          generatedId: false,
          name: 'location_relationships',
        },
        {
          _id: '68ddecdbc9474e23bb5e9159',
          type: 'generatedid',
          label: 'Document ID',
          noLabel: false,
          required: false,
          showInCard: false,
          style: '',
          generatedId: false,
          name: 'document_id',
        },
        {
          content: '68ec577980a3354966fb293c',
          _id: '68ed110f2bbc3dca9918f4bc',
          type: 'relationship',
          label: 'Hierarchical Relationships',
          noLabel: false,
          required: false,
          showInCard: true,
          style: '',
          relationType: '68da99b961bceda4fe0d6ddd',
          inherit: {
            property: '68ec57a480a3354966fb2971',
            type: 'relationship',
          },
          generatedId: false,
          name: 'hierarchical_relationships',
        },
      ],
      commonProperties: [
        {
          _id: '68ddecdbc9474e23bb5e915a',
          label: 'Title',
          name: 'title',
          type: 'text',
          isCommonProperty: true,
        },
        {
          _id: '68ddecdbc9474e23bb5e915b',
          label: 'Date added',
          name: 'creationDate',
          type: 'date',
          isCommonProperty: true,
        },
        {
          _id: '68ddecdbc9474e23bb5e915c',
          label: 'Date modified',
          name: 'editDate',
          type: 'date',
          isCommonProperty: true,
        },
      ],
      entityViewPage: '',
      name: 'Emergency Incident Report Template',
      __v: 10,
    },
    {
      _id: '68ec577980a3354966fb293c',
      color: '#C03B22',
      properties: [
        {
          content: '68ec5bf780a3354966fb2c25',
          _id: '68ec57a480a3354966fb2971',
          type: 'relationship',
          label: 'Relationship n-2',
          noLabel: false,
          required: false,
          showInCard: true,
          style: '',
          relationType: '68da99b961bceda4fe0d6ddd',
          inherit: {
            property: '68ed10e32bbc3dca9918f3c7',
            type: 'relationship',
          },
          generatedId: false,
          name: 'relationship_n-2',
        },
      ],
      commonProperties: [
        {
          _id: '68ec577980a3354966fb293d',
          label: 'Title',
          name: 'title',
          type: 'text',
          isCommonProperty: true,
        },
        {
          _id: '68ec577980a3354966fb293e',
          label: 'Date added',
          name: 'creationDate',
          type: 'date',
          isCommonProperty: true,
        },
        {
          _id: '68ec577980a3354966fb293f',
          label: 'Date modified',
          name: 'editDate',
          type: 'date',
          isCommonProperty: true,
        },
      ],
      entityViewPage: '',
      name: 'middle',
      __v: 4,
    },
    {
      _id: '68ec5bf780a3354966fb2c25',
      color: '#C03B22',
      properties: [
        {
          content: '5bfbb1a0471dd0fc16ada146',
          _id: '68ed10e32bbc3dca9918f3c7',
          type: 'relationship',
          label: 'Relationship n-1',
          noLabel: false,
          required: false,
          showInCard: true,
          style: '',
          relationType: '68da99b961bceda4fe0d6ddd',
          inherit: {
            property: '68d6f62891b591b7432b2b4b',
            type: 'multiselect',
          },
          generatedId: false,
          name: 'relationship_n-1',
        },
      ],
      commonProperties: [
        {
          _id: '68ec5bf780a3354966fb2c27',
          label: 'Title',
          name: 'title',
          type: 'text',
          isCommonProperty: true,
        },
        {
          _id: '68ec5bf780a3354966fb2c28',
          label: 'Date added',
          name: 'creationDate',
          type: 'date',
          isCommonProperty: true,
        },
        {
          _id: '68ec5bf780a3354966fb2c29',
          label: 'Date modified',
          name: 'editDate',
          type: 'date',
          isCommonProperty: true,
        },
      ],
      entityViewPage: '',
      name: 'extra level',
      __v: 2,
    },
  ],
  settings: {
    dateFormat: 'DDD',
    site_name: 'Uwazi',
    languages: [
      {
        key: 'en',
        label: 'English',
        default: true,
      },
    ],
  },
  thesauri: [
    {
      _id: '68d6ed4891b591b7432b276b',
      name: 'Verbs',
      values: [
        {
          label: 'Acknowledging',
          id: '765ab6ca-56a1-4948-9dc9-17fc0aa30843',
        },
        {
          label: 'Again',
          id: '9e22a1af-75d7-49a2-b9d8-9ec77939b630',
        },
        {
          label: 'Confirming',
          id: '240c244f-a736-4ad4-b777-e690e3ff78f0',
        },
        {
          label: 'Expressing',
          id: '6c744926-bf38-4f98-8c74-cf6b7280863c',
        },
        {
          label: 'grouped',
          values: [
            {
              label: 'verb1',
              id: 'e1b9944b-43ef-4989-837b-b3df79284b00',
            },
            {
              label: 'verb2',
              id: '8c418311-1244-4777-800a-65729b8c17a8',
            },
          ],
          id: '68979984-35ac-4b98-abf9-28eac857749c',
        },
      ],
      __v: 6,
    },
  ],
  currentUser: {
    _id: '58ada34d299e82674854510f',
    username: 'admin',
    email: 'admin@uwazi.com',
    __v: 1,
    role: 'admin',
    groups: [],
  },
};
