//DATA
export const ADD_LINK = 'ADD_LINK';
export const REMOVE_LINK = 'REMOVE_LINK';
// export const REORDER_LINK = 'REORDER_LINK';
export const NAVLINKS_SAVED = 'NAVLINKS_SAVED';

//UI
export const EDIT_LINK = 'EDIT_LINK';
export const SHOW_REMOVE_LINK_CONFIRM = 'SHOW_REMOVE_LINK_CONFIRM';
export const HIDE_REMOVE_LINK_CONFIRM = 'HIDE_REMOVE_LINK_CONFIRM';
export const SAVING_NAVLINKS = 'SAVING_NAVLINKS';
