"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.default = void 0;var _default = {
  checkbox: 'check',
  numeric: 'calculator',
  relationship: 'link',
  relationshipfilter: 'filter',
  select: 'sort',
  multiselect: 'list',
  date: 'calendar',
  text: 'font',
  markdown: 'file',
  nested: 'cubes',
  multidate: 'calendar',
  multidaterange: 'calendar',
  daterange: 'calendar',
  image: 'image',
  preview: 'passport',
  media: 'video',
  geolocation: 'map-marker',
  link: 'link' };exports.default = _default;