export default [
  { label: 'Abkhazian', key: 'ab' },
  { label: 'Afar', key: 'aa' },
  { label: 'Afrikaans', key: 'af' },
  { label: 'Akan', key: 'ak' },
  { label: 'Albanian', key: 'sq' },
  { label: 'Amharic', key: 'am' },
  { label: 'Arabic', key: 'ar' },
  { label: 'Aragonese', key: 'an' },
  { label: 'Armenian', key: 'hy' },
  { label: 'Assamese', key: 'as' },
  { label: 'Avaric', key: 'av' },
  { label: 'Avestan', key: 'ae' },
  { label: 'Aymara', key: 'ay' },
  { label: 'Azerbaijani', key: 'az' },
  { label: 'Bambara', key: 'bm' },
  { label: 'Bashkir', key: 'ba' },
  { label: 'Basque', key: 'eu' },
  { label: 'Belarusian', key: 'be' },
  { label: 'Bengali (Bangla)', key: 'bn' },
  { label: 'Bihari', key: 'bh' },
  { label: 'Bislama', key: 'bi' },
  { label: 'Bosnian', key: 'bs' },
  { label: 'Breton', key: 'br' },
  { label: 'Bulgarian', key: 'bg' },
  { label: 'Burmese', key: 'my' },
  { label: 'Catalan', key: 'ca' },
  { label: 'Chamorro', key: 'ch' },
  { label: 'Chechen', key: 'ce' },
  { label: 'Chichewa, Chewa, Nyanja', key: 'ny' },
  { label: 'Chinese', key: 'zh' },
  { label: 'Chinese (Simplified)', key: 'zh-Hans' },
  { label: 'Chinese (Traditional)', key: 'zh-Hant' },
  { label: 'Chuvash', key: 'cv' },
  { label: 'Cornish', key: 'kw' },
  { label: 'Corsican', key: 'co' },
  { label: 'Cree', key: 'cr' },
  { label: 'Croatian', key: 'hr' },
  { label: 'Czech', key: 'cs' },
  { label: 'Danish', key: 'da' },
  { label: 'Divehi, Dhivehi, Maldivian', key: 'dv' },
  { label: 'Dutch', key: 'nl' },
  { label: 'Dzongkha', key: 'dz' },
  { label: 'English', key: 'en' },
  { label: 'Esperanto', key: 'eo' },
  { label: 'Estonian', key: 'et' },
  { label: 'Ewe', key: 'ee' },
  { label: 'Faroese', key: 'fo' },
  { label: 'Fijian', key: 'fj' },
  { label: 'Finnish', key: 'fi' },
  { label: 'French', key: 'fr' },
  { label: 'Fula, Fulah, Pulaar, Pular', key: 'ff' },
  { label: 'Galician', key: 'gl' },
  { label: 'Gaelic Scottish', key: 'gd' },
  { label: 'Gaelic (Manx)', key: 'gv' },
  { label: 'Georgian', key: 'ka' },
  { label: 'German', key: 'de' },
  { label: 'Greek', key: 'el' },
  { label: 'Guarani', key: 'gn' },
  { label: 'Gujarati', key: 'gu' },
  { label: 'Haitian Creole', key: 'ht' },
  { label: 'Hausa', key: 'ha' },
  { label: 'Hebrew', key: 'he' },
  { label: 'Herero', key: 'hz' },
  { label: 'Hindi', key: 'hi' },
  { label: 'Hiri Motu', key: 'ho' },
  { label: 'Hungarian', key: 'hu' },
  { label: 'Icelandic', key: 'is' },
  { label: 'Ido', key: 'io' },
  { label: 'Igbo', key: 'ig' },
  { label: 'Indonesian', key: 'in' },
  { label: 'Interlingua', key: 'ia' },
  { label: 'Interlingue', key: 'ie' },
  { label: 'Inuktitut', key: 'iu' },
  { label: 'Inupiak', key: 'ik' },
  { label: 'Irish', key: 'ga' },
  { label: 'Italian', key: 'it' },
  { label: 'Japanese', key: 'ja' },
  { label: 'Javanese', key: 'jv' },
  { label: 'Kalaallisut, Greenlandic', key: 'kl' },
  { label: 'Kannada', key: 'kn' },
  { label: 'Kanuri', key: 'kr' },
  { label: 'Kashmiri', key: 'ks' },
  { label: 'Kazakh', key: 'kk' },
  { label: 'Khmer', key: 'km' },
  { label: 'Kikuyu', key: 'ki' },
  { label: 'Kinyarwanda (Rwanda)', key: 'rw' },
  { label: 'Kirundi', key: 'rn' },
  { label: 'Kyrgyz', key: 'ky' },
  { label: 'Komi', key: 'kv' },
  { label: 'Kongo', key: 'kg' },
  { label: 'Korean', key: 'ko' },
  { label: 'Kurdish', key: 'ku' },
  { label: 'Kwanyama', key: 'kj' },
  { label: 'Lao', key: 'lo' },
  { label: 'Latin', key: 'la' },
  { label: 'Latvian (Lettish)', key: 'lv' },
  { label: 'Limburgish (Limburger)', key: 'li' },
  { label: 'Lingala', key: 'ln' },
  { label: 'Lithuanian', key: 'lt' },
  { label: 'Luga-Katanga', key: 'lu' },
  { label: 'Luganda, Ganda', key: 'lg' },
  { label: 'Luxembourgish', key: 'lb' },
  { label: 'Macedonian', key: 'mk' },
  { label: 'Malagasy', key: 'mg' },
  { label: 'Malay', key: 'ms' },
  { label: 'Malayalam', key: 'ml' },
  { label: 'Maltese', key: 'mt' },
  { label: 'Maori', key: 'mi' },
  { label: 'Marathi', key: 'mr' },
  { label: 'Marshallese', key: 'mh' },
  { label: 'Moldavian', key: 'mo' },
  { label: 'Mongolian', key: 'mn' },
  { label: 'Nauru', key: 'na' },
  { label: 'Navajo', key: 'nv' },
  { label: 'Ndonga', key: 'ng' },
  { label: 'Northern Ndebele', key: 'nd' },
  { label: 'Nepali', key: 'ne' },
  { label: 'Norwegian', key: 'no' },
  { label: 'Norwegian bokmål', key: 'nb' },
  { label: 'Norwegian nynorsk', key: 'nn' },
  { label: 'Occitan', key: 'oc' },
  { label: 'Ojibwe', key: 'oj' },
  { label: 'Old Church Slavonic, Old Bulgarian', key: 'cu' },
  { label: 'Oriya', key: 'or' },
  { label: 'Oromo (Afaan Oromo)', key: 'om' },
  { label: 'Ossetian', key: 'os' },
  { label: 'Pāli', key: 'pi' },
  { label: 'Pashto, Pushto', key: 'ps' },
  { label: 'Persian (Farsi)', key: 'fa' },
  { label: 'Polish', key: 'pl' },
  { label: 'Portuguese', key: 'pt' },
  { label: 'Punjabi (Eastern)', key: 'pa' },
  { label: 'Quechua', key: 'qu' },
  { label: 'Romansh', key: 'rm' },
  { label: 'Romanian', key: 'ro' },
  { label: 'Russian', key: 'ru' },
  { label: 'Sami', key: 'se' },
  { label: 'Samoan', key: 'sm' },
  { label: 'Sango', key: 'sg' },
  { label: 'Sanskrit', key: 'sa' },
  { label: 'Serbian', key: 'sr' },
  { label: 'Serbo-Croatian', key: 'sh' },
  { label: 'Sesotho', key: 'st' },
  { label: 'Setswana', key: 'tn' },
  { label: 'Shona', key: 'sn' },
  { label: 'Sichuan Yi, Nuosu', key: 'ii' },
  { label: 'Sindhi', key: 'sd' },
  { label: 'Sinhalese', key: 'si' },
  { label: 'Siswati, Swati', key: 'ss' },
  { label: 'Slovak', key: 'sk' },
  { label: 'Slovenian', key: 'sl' },
  { label: 'Somali', key: 'so' },
  { label: 'Southern Ndebele', key: 'nr' },
  { label: 'Spanish', key: 'es' },
  { label: 'Sundanese', key: 'su' },
  { label: 'Swahili (Kiswahili)', key: 'sw' },
  { label: 'Swedish', key: 'sv' },
  { label: 'Tagalog', key: 'tl' },
  { label: 'Tahitian', key: 'ty' },
  { label: 'Tajik', key: 'tg' },
  { label: 'Tamil', key: 'ta' },
  { label: 'Tatar', key: 'tt' },
  { label: 'Telugu', key: 'te' },
  { label: 'Thai', key: 'th' },
  { label: 'Tibetan', key: 'bo' },
  { label: 'Tigrinya', key: 'ti' },
  { label: 'Tonga', key: 'to' },
  { label: 'Tsonga', key: 'ts' },
  { label: 'Turkish', key: 'tr' },
  { label: 'Turkmen', key: 'tk' },
  { label: 'Twi', key: 'tw' },
  { label: 'Uyghur', key: 'ug' },
  { label: 'Ukrainian', key: 'uk' },
  { label: 'Urdu', key: 'ur' },
  { label: 'Uzbek', key: 'uz' },
  { label: 'Venda', key: 've' },
  { label: 'Vietnamese', key: 'vi' },
  { label: 'Volapük', key: 'vo' },
  { label: 'Wallon', key: 'wa' },
  { label: 'Welsh', key: 'cy' },
  { label: 'Wolof', key: 'wo' },
  { label: 'Western Frisian', key: 'fy' },
  { label: 'Xhosa', key: 'xh' },
  { label: 'Yiddish', key: 'yi' },
  { label: 'Yoruba', key: 'yo' },
  { label: 'Zhuang, Chuang', key: 'za' },
  { label: 'Zulu', key: 'zu' },
];
