export enum PXErrorCode {
  DEFAULT_PARAGRAPH_NOT_FOUND = 'DEFAULT_PARAGRAPH_NOT_FOUND',
  LANGUAGE_NOT_FOUND = 'LANGUAGE_NOT_FOUND',
  EXTRACTOR_NOT_FOUND = 'EXTRACTOR_NOT_FOUND',
  SEGMENTATION_FILES_NOT_FOUND = 'FILES_NOT_FOUND',
  LANGUAGES_NOT_FOUND = 'LANGUAGES_NOT_FOUND',
  DOCUMENTS_NOT_FOUND = 'DOCUMENTS_NOT_FOUND',
  TARGET_TEMPLATE_NOT_FOUND = 'TARGET_TEMPLATE_NOT_FOUND',
  SOURCE_TEMPLATE_NOT_FOUND = 'SOURCE_TEMPLATE_NOT_FOUND',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  SEGMENTATIONS_UNAVAILABLE = 'SEGMENTATIONS_UNAVAILABLE',
  TARGET_TEMPLATE_INVALID = 'TARGET_TEMPLATE_INVALID',
  ENTITY_INVALID = 'ENTITY_INVALID',
  TARGET_SOURCE_TEMPLATE_EQUAL = 'TARGET_SOURCE_TEMPLATE_EQUAL',
  EXTRACTION_ID_INVALID = 'EXTRACTION_ID_INVALID',
}

export class PXValidationError extends Error {
  static codes = PXErrorCode;

  static name = 'PXValidationError';

  constructor(
    public code: PXErrorCode,
    message: string,
    options?: ErrorOptions
  ) {
    super(message, options);
    this.name = PXValidationError.name;
  }
}
