export enum PXErrorCode {
  DEFAULT_PARAGRAPH_NOT_FOUND = 'DEFAULT_PARAGRAPH_NOT_FOUND',
  LANGUAGE_NOT_FOUND = 'LANGUAGE_NOT_FOUND',
  EXTRACTOR_NOT_FOUND = 'EXTRACTOR_NOT_FOUND',
  SEGMENTATION_FILES_NOT_FOUND = 'FILES_NOT_FOUND',
  LANGUAGES_NOT_FOUND = 'LANGUAGES_NOT_FOUND',
  DOCUMENTS_NOT_FOUND = 'DOCUMENTS_NOT_FOUND',
  TARGET_TEMPLATE_NOT_FOUND = 'TARGET_TEMPLATE_NOT_FOUND',
  SOURCE_TEMPLATE_NOT_FOUND = 'SOURCE_TEMPLATE_NOT_FOUND',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  SEGMENTATIONS_UNAVAILABLE = 'SEGMENTATIONS_UNAVAILABLE',
  TARGET_TEMPLATE_INVALID = 'TARGET_TEMPLATE_INVALID',
  ENTITY_INVALID = 'ENTITY_INVALID',
  TARGET_SOURCE_TEMPLATE_EQUAL = 'TARGET_SOURCE_TEMPLATE_EQUAL',
  EXTRACTION_ID_INVALID = 'EXTRACTION_ID_INVALID',
  SOURCE_ENTITY_DOES_NOT_EXIST_ANYMORE = 'SOURCE_ENTITY_DOES_NOT_EXIST_ANYMORE',
  PARAGRAPH_PROPERTY_DOES_NOT_EXIST = 'PARAGRAPH_PROPERTY_DOES_NOT_EXIST',
  PARAGRAPH_NUMBER_PROPERTY_DOES_NOT_EXIST = 'PARAGRAPH_NUMBER_PROPERTY_DOES_NOT_EXIST',
  PARAGRAPH_PROPERTY_IS_NOT_OF_RICH_TEXT = 'PARAGRAPH_PROPERTY_IS_NOT_OF_RICH_TEXT',
  PARAGRAPH_NUMBER_PROPERTY_IS_NOT_A_NUMBER = 'PARAGRAPH_NUMBER_PROPERTY_IS_NOT_A_NUMBER',
  SOURCE_RELATIONSHIP_TYPE_DOES_NOT_EXIST = 'SOURCE_RELATIONSHIP_TYPE_NOT_FOUND',
  TARGET_RELATIONSHIP_TYPE_DOES_NOT_EXIST = 'TARGET_RELATIONSHIP_TYPE_DOES_NOT_EXIST',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  DOCUMENT_IS_NOT_READY_TO_BE_USED = 'DOCUMENT_IS_NOT_READY_TO_BE_USED',
  DOCUMENT_DO_NOT_HAVE_CHANGE_CRITERIA = 'DOCUMENT_DO_NOT_HAVE_CHANGE_CRITERIA',
  DOCUMENT_DO_NOT_MEET_ENTITY_STATUS_CRITERIA = 'DOCUMENT_DO_NOT_MEET_ENTITY_STATUS_CRITERIA',
  CANNOT_MANAGE_ENTITY_STATUS_FOR_SOURCE_TEMPLATE_NOT_EXISTING = 'CANNOT_MANAGE_ENTITY_STATUS_FOR_SOURCE_TEMPLATE_NOT_EXISTING',
  CANNOT_MANAGE_ENTITY_STATUS_FOR_SOURCE_TEMPLATE_NOT_MATCHING_CRITERIA = 'CANNOT_MANAGE_ENTITY_STATUS_FOR_SOURCE_TEMPLATE_NOT_MATCHING_CRITERIA',
  EXTRACTOR_ALREADY_EXISTS = 'EXTRACTOR_ALREADY_EXISTS',
  CANNOT_DELETE_EXTRACTOR_THAT_DOES_NOT_EXIST = 'CANNOT_DELETE_EXTRACTOR_THAT_DOES_NOT_EXIST',
}

export class PXValidationError extends Error {
  static codes = PXErrorCode;

  static name = 'PXValidationError';

  constructor(
    public code: PXErrorCode,
    message: string,
    options?: ErrorOptions
  ) {
    super(message, options);
    this.name = PXValidationError.name;
  }
}
