services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:22
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - DATABASE_NAME=uwazi_development
      - DBHOST=uwazi-mongo
      - ELASTICSEARCH_URL=http://uwazi-elasticsearch:9200
      - INDEX_NAME=uwazi_development
      - REDIS_HOST=uwazi-redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=uwazi-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=uwazi_development
      - S3_ENDPOINT=http://uwazi-s3:9000
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - S3_BUCKET=uwazi-development
    depends_on:
      - uwazi-elasticsearch
      - uwazi-mongo
      - uwazi-redis
      - uwazi-postgres
      - uwazi-s3
