export const ADD_PROPERTY = 'ADD_PROPERTY';
export const ADD_PLACEHOLDER = 'ADD_PLACEHOLDER';
export const REMOVE_PROPERTY = 'REMOVE_PROPERTY';
export const REORDER_PROPERTY = 'REORDER_PROPERTY';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const SELECT_PROPERTY = 'SELECT_PROPERTY';
export const SET_TEMPLATES = 'SET_TEMPLATES';
