/* eslint-disable @typescript-eslint/no-use-before-define */
/* eslint-disable import/exports-last */
/* eslint-disable no-continue */
/* eslint-disable no-plusplus */
/* eslint-disable no-restricted-syntax */
/* eslint-disable max-statements */
import { ObjectId } from 'mongodb';
import type { DiffResult } from './DocumentTracker';

/**
 * Builds a MongoDB aggregation pipeline from a DiffResult object.
 * This is used for complex updates, particularly for arrays of objects with `_id`s,
 * which cannot be handled by a simple update document.
 * @param diff The DiffResult object generated by the DocumentTracker.
 * @returns A MongoDB update document or an aggregation pipeline.
 */
export function buildPipelineFromDiff(
  diff: DiffResult
): Record<string, any> | Record<string, any>[] {
  const needsPipeline =
    diff.$pull || diff.$push || (diff.$set && Object.keys(diff.$set).some(k => k.includes('.$[')));

  // If a pipeline is not required, return the raw update document.
  if (!needsPipeline) {
    const updateDoc: Record<string, any> = {};
    if (diff.$set && Object.keys(diff.$set).length) updateDoc.$set = diff.$set;
    if (diff.$unset && Object.keys(diff.$unset).length) updateDoc.$unset = diff.$unset;
    if (diff.$push && Object.keys(diff.$push).length) updateDoc.$push = diff.$push;
    if (diff.$pull && Object.keys(diff.$pull).length) updateDoc.$pull = diff.$pull;
    return updateDoc;
  }

  // Build the aggregation pipeline.
  const stages: Record<string, any>[] = [];

  // Add the $set stage for top-level fields.
  const baseSet = Object.entries(diff.$set || {})
    .filter(([key]) => !key.includes('.$['))
    .reduce((acc, [key, value]) => ({ ...acc, [key]: value }), {});
  if (Object.keys(baseSet).length) {
    stages.push({ $set: baseSet });
  }

  // Handle array operations ($pull, $push, arrayFilters).
  const arrayPaths = new Set<string>();
  if (diff.$pull) Object.keys(diff.$pull).forEach(p => arrayPaths.add(p));
  if (diff.$push) Object.keys(diff.$push).forEach(p => arrayPaths.add(p));
  if (diff.$set) {
    Object.keys(diff.$set).forEach(key => {
      const match = key.match(/(.+)\.\$\[/);
      if (match) {
        arrayPaths.add(match[1]);
      }
    });
  }

  // Map array filter element names to their ObjectId values for efficient lookup.
  const elemNameToId = new Map<string, ObjectId>();
  (diff.arrayFilters || []).forEach(filter => {
    const key = Object.keys(filter)[0];
    const elemNameMatch = key.match(/^(.+)\._id$/);
    if (elemNameMatch) {
      const elemName = elemNameMatch[1];
      elemNameToId.set(elemName, filter[key]);
    }
  });

  for (const path of arrayPaths) {
    const removedIds = diff.$pull?.[path]?._id?.$in || [];
    const pushedItems = diff.$push?.[path]?.$each || [];

    const updatesByIdHex = buildArrayFilterUpdates(diff.$set || {}, path, elemNameToId);

    // Build the $set expression for this specific array.
    let arrayExpression: Record<string, any> | string = `$${path}`;

    if (removedIds.length > 0) {
      arrayExpression = {
        $filter: {
          input: arrayExpression,
          as: 'a',
          cond: { $not: { $in: ['$$a._id', removedIds] } },
        },
      };
    }

    if (Object.keys(updatesByIdHex).length > 0) {
      arrayExpression = {
        $map: {
          input: arrayExpression,
          as: 'a',
          in: {
            $switch: {
              branches: Object.entries(updatesByIdHex).map(([idHex, update]) => ({
                case: { $eq: ['$$a._id', new ObjectId(idHex)] },
                then: { $mergeObjects: ['$$a', update] },
              })),
              default: '$$a',
            },
          },
        },
      };
    }

    if (pushedItems.length > 0) {
      arrayExpression = { $concatArrays: [arrayExpression, pushedItems] };
    }

    stages.push({ $set: { [path]: arrayExpression } });
  }

  // Add the final $unset stage for top-level fields.
  if (diff.$unset && Object.keys(diff.$unset).length) {
    stages.push({ $unset: Object.keys(diff.$unset) });
  }

  return stages;
}

/**
 * Helper function to parse $set fields with array filters and group them by document ID.
 * @param setEntries All entries from the $set operator.
 * @param path The array path being processed.
 * @param elemNameToId A map of array filter names to ObjectIds.
 * @returns A map of `idHex` to the object of updates for that document.
 */
function buildArrayFilterUpdates(
  setEntries: Record<string, any>,
  path: string,
  elemNameToId: Map<string, ObjectId>
): Record<string, any> {
  const updatesByIdHex: Record<string, any> = {};

  for (const [fullKey, value] of Object.entries(setEntries)) {
    const match = fullKey.match(new RegExp(`^${path}\\.\\$?\\[(.+)\\]\\.?(.+)?$`));
    if (!match) continue;

    const [, elemName, fieldPath] = match;
    const idObj = elemNameToId.get(elemName);
    if (!idObj) continue;

    const idHex = idObj.toHexString();
    let currentUpdate = updatesByIdHex[idHex] || {};

    if (fieldPath) {
      const parts = fieldPath.split('.');
      let cursor = currentUpdate;
      for (let i = 0; i < parts.length - 1; i++) {
        const part = parts[i];
        cursor[part] = cursor[part] || {};
        cursor = cursor[part];
      }
      cursor[parts[parts.length - 1]] = value;
    } else {
      // This case handles setting the entire sub-document.
      currentUpdate = value;
    }

    updatesByIdHex[idHex] = currentUpdate;
  }
  return updatesByIdHex;
}
