/* eslint-disable no-plusplus */
/* eslint-disable no-continue */
/* eslint-disable no-restricted-syntax */
import { ObjectId } from 'mongodb';
import type { DiffResult } from './DocumentTracker';

/**
 * Builds a MongoDB update document or an aggregation pipeline from a DiffResult object.
 * This function determines the most efficient operation based on the detected changes.
 * A simple update document is used for top-level field changes, while a pipeline is
 * built for complex array mutations.
 *
 * @param diff The DiffResult object generated by the DocumentTracker.
 * @returns A MongoDB update document or an aggregation pipeline.
 */
export function buildPipelineFromDiff(
  diff: DiffResult
): Record<string, any> | Record<string, any>[] {
  const hasArrayOperations =
    diff.$pull || diff.$push || (diff.$set && Object.keys(diff.$set).some(k => k.includes('.$[')));

  // If there are no array-specific changes, return a simple update document.
  if (!hasArrayOperations) {
    const updateDoc: Record<string, any> = {};
    if (diff.$set && Object.keys(diff.$set).length) updateDoc.$set = diff.$set;
    if (diff.$unset && Object.keys(diff.$unset).length) updateDoc.$unset = diff.$unset;
    return updateDoc;
  }

  // Otherwise, an aggregation pipeline is required for atomic array operations.
  const stages: Record<string, any>[] = [];
  const arrayFilterMap = new Map<string, ObjectId>();

  // Extract array filters to map element names to their ObjectIds.
  (diff.arrayFilters || []).forEach(filter => {
    const key = Object.keys(filter)[0];
    const elemNameMatch = key.match(/^(.+)\._id$/);
    if (elemNameMatch) {
      arrayFilterMap.set(elemNameMatch[1], filter[key]);
    }
  });

  // Separate top-level `$set` fields from array-specific `$set` fields
  const topLevelSet: Record<string, any> = {};
  const arraySet: Record<string, any> = {};
  for (const [key, value] of Object.entries(diff.$set || {})) {
    if (key.includes('.$[')) {
      arraySet[key] = value;
    } else {
      topLevelSet[key] = value;
    }
  }

  // Identify all unique array paths that need processing
  const arrayPaths = new Set<string>();
  if (diff.$pull) Object.keys(diff.$pull).forEach(p => arrayPaths.add(p));
  if (diff.$push) Object.keys(diff.$push).forEach(p => arrayPaths.add(p));
  Object.keys(arraySet).forEach(key => {
    const match = key.match(/(.+)\.\$\[/);
    if (match) {
      arrayPaths.add(match[1]);
    }
  });

  // Start with a $set stage for top-level changes if they exist.
  if (Object.keys(topLevelSet).length) {
    stages.push({ $set: topLevelSet });
  }

  // Iterate over each unique array path to build the update expression.
  for (const path of arrayPaths) {
    let arrayExpression: Record<string, any> | string = `$${path}`;

    // 1. Handle $pull operations first to remove elements.
    const removedIds = diff.$pull?.[path]?._id?.$in || [];
    if (removedIds.length > 0) {
      arrayExpression = {
        $filter: {
          input: arrayExpression,
          as: 'a',
          cond: { $not: { $in: ['$$a._id', removedIds] } },
        },
      };
    }

    // 2. Build the array-in-place updates using $map and $switch.
    const updatesByIdHex = new Map<string, Record<string, any>>();
    for (const [fullKey, value] of Object.entries(arraySet)) {
      const match = fullKey.match(new RegExp(`^${path}\\.\\$?\\[(.+)\\]\\.?(.+)?$`));
      if (!match) continue;

      const [, elemName, fieldPath] = match;
      const idObj = arrayFilterMap.get(elemName);
      if (!idObj) continue;

      const idHex = idObj.toHexString();
      let currentUpdate = updatesByIdHex.get(idHex) || {};

      if (fieldPath) {
        const parts = fieldPath.split('.');
        let cursor = currentUpdate;
        for (let i = 0; i < parts.length - 1; i++) {
          const part = parts[i];
          cursor[part] = cursor[part] || {};
          cursor = cursor[part];
        }
        cursor[parts[parts.length - 1]] = value;
      } else {
        // This handles setting the entire sub-document.
        currentUpdate = value;
      }

      updatesByIdHex.set(idHex, currentUpdate);
    }

    if (updatesByIdHex.size > 0) {
      arrayExpression = {
        $map: {
          input: arrayExpression,
          as: 'a',
          in: {
            $switch: {
              branches: Array.from(updatesByIdHex).map(([idHex, update]) => ({
                case: { $eq: ['$$a._id', new ObjectId(idHex)] },
                then: { $mergeObjects: ['$$a', update] },
              })),
              default: '$$a',
            },
          },
        },
      };
    }

    // 3. Handle $push operations to append new elements.
    const pushedItems = diff.$push?.[path]?.$each || [];
    if (pushedItems.length > 0) {
      arrayExpression = { $concatArrays: [arrayExpression, pushedItems] };
    }

    // Add the final array update stage for this path.
    if (typeof arrayExpression !== 'string') {
      stages.push({ $set: { [path]: arrayExpression } });
    }
  }

  // Add the final $unset stage for top-level fields.
  if (diff.$unset && Object.keys(diff.$unset).length) {
    stages.push({ $unset: Object.keys(diff.$unset) });
  }

  return stages;
}
