export const SET_REFERENCES = 'SET_REFERENCES';
export const SET_DOCUMENT = 'SET_DOCUMENT';
export const RESET_DOCUMENT_VIEWER = 'RESET_DOCUMENT_VIEWER';

export const SET_SELECTION = 'SET_SELECTION';
export const UNSET_SELECTION = 'UNSET_SELECTION';

//MENU
export const LOAD_DEFAULT_VIEWER_MENU = 'LOAD_DEFAULT_VIEWER_MENU';

//UI
export const OPEN_REFERENCE_PANEL = 'OPEN_REFERENCE_PANEL';
