export const SET_REFERENCES = 'SET_REFERENCES';
export const SET_DOCUMENT = 'SET_DOCUMENT';
export const SET_TARGET_DOCUMENT = 'SET_TARGET_DOCUMENT';
export const SET_VIEWER_RESULTS = 'SET_VIEWER_RESULTS';
export const RESET_DOCUMENT_VIEWER = 'RESET_DOCUMENT_VIEWER';

export const SET_SELECTION = 'SET_SELECTION';
export const UNSET_SELECTION = 'UNSET_SELECTION';
export const SET_TARGET_SELECTION = 'SET_TARGET_SELECTION';
export const UNSET_TARGET_SELECTION = 'UNSET_TARGET_SELECTION';

//REFERENCES
export const ADD_CREATED_REFERENCE = 'ADD_CREATED_REFERENCE';

//MENU
export const LOAD_DEFAULT_VIEWER_MENU = 'LOAD_DEFAULT_VIEWER_MENU';

//UI
export const OPEN_REFERENCE_PANEL = 'OPEN_REFERENCE_PANEL';
export const OPEN_TARGET_REFERENCE_PANEL = 'OPEN_TARGET_REFERENCE_PANEL';
export const VIEWER_SEARCHING = 'VIEWER_SEARCHING';
export const SELECT_TARGET_DOCUMENT = 'SELECT_TARGET_DOCUMENT';
export const RESET_REFERENCE_CREATION = 'RESET_REFERENCE_CREATION';
