import { LanguageSchema } from 'shared/types/commonTypes';

const elasticLanguages: {
  [index: string]: { franc: string; elastic: string; ISO639_1: string | null };
} = {
  arb: { franc: 'arb', elastic: 'arabic', ISO639_1: 'ar' },
  bul: { franc: 'bul', elastic: 'bulgarian', ISO639_1: 'bg' },
  cat: { franc: 'cat', elastic: 'catalan', ISO639_1: 'ca' },
  cjk: { franc: 'cjk', elastic: 'cjk', ISO639_1: null },
  ckb: { franc: 'ckb', elastic: 'sorani', ISO639_1: null },
  ces: { franc: 'ces', elastic: 'czech', ISO639_1: 'cs' },
  dan: { franc: 'dan', elastic: 'danish', ISO639_1: 'da' },
  deu: { franc: 'deu', elastic: 'german', ISO639_1: 'de' },
  ell: { franc: 'ell', elastic: 'greek', ISO639_1: 'el' },
  eng: { franc: 'eng', elastic: 'english', ISO639_1: 'en' },
  eus: { franc: 'eus', elastic: 'basque', ISO639_1: 'eu' },
  fas: { franc: 'fas', elastic: 'persian', ISO639_1: 'fa' },
  fin: { franc: 'fin', elastic: 'finnish', ISO639_1: 'fi' },
  fra: { franc: 'fra', elastic: 'french', ISO639_1: 'fr' },
  gle: { franc: 'gle', elastic: 'irish', ISO639_1: 'ga' },
  glg: { franc: 'glg', elastic: 'galician', ISO639_1: 'gl' },
  hin: { franc: 'hin', elastic: 'hindi', ISO639_1: 'hi' },
  hun: { franc: 'hun', elastic: 'hungarian', ISO639_1: 'hu' },
  hye: { franc: 'hye', elastic: 'armenian', ISO639_1: 'hy' },
  ind: { franc: 'ind', elastic: 'indonesian', ISO639_1: 'id' },
  ita: { franc: 'ita', elastic: 'italian', ISO639_1: 'it' },
  lav: { franc: 'lav', elastic: 'latvian', ISO639_1: 'lv' },
  lit: { franc: 'lit', elastic: 'lithuanian', ISO639_1: 'lt' },
  nld: { franc: 'nld', elastic: 'dutch', ISO639_1: 'nl' },
  nno: { franc: 'nno', elastic: 'norwegian', ISO639_1: 'nn' },
  nob: { franc: 'nob', elastic: 'norwegian', ISO639_1: 'nb' },
  por: { franc: 'por', elastic: 'portuguese', ISO639_1: 'pt' },
  ron: { franc: 'ron', elastic: 'romanian', ISO639_1: 'ro' },
  rus: { franc: 'rus', elastic: 'russian', ISO639_1: 'ru' },
  spa: { franc: 'spa', elastic: 'spanish', ISO639_1: 'es' },
  swe: { franc: 'swe', elastic: 'swedish', ISO639_1: 'sv' },
  tha: { franc: 'tha', elastic: 'thai', ISO639_1: 'th' },
  tur: { franc: 'tur', elastic: 'turkish', ISO639_1: 'tr' },
};

const allLanguages: LanguageSchema[] = [
  { label_en: 'Abkhazian', label: 'Abkhazian', key: 'ab' },
  { label_en: 'Afar', label: 'Afar', key: 'aa' },
  { label_en: 'Afrikaans', label: 'Afrikaans', key: 'af' },
  { label_en: 'Akan', label: 'Akan', key: 'ak' },
  { label_en: 'Albanian', label: 'Albanian', key: 'sq' },
  { label_en: 'Amharic', label: 'Amharic', key: 'am' },
  { label_en: 'Arabic', label: 'Arabic', key: 'ar', rtl: true },
  { label_en: 'Aragonese', label: 'Aragonese', key: 'an' },
  { label_en: 'Armenian', label: 'Armenian', key: 'hy' },
  { label_en: 'Assamese', label: 'Assamese', key: 'as' },
  { label_en: 'Avaric', label: 'Avaric', key: 'av' },
  { label_en: 'Avestan', label: 'Avestan', key: 'ae' },
  { label_en: 'Aymara', label: 'Aymara', key: 'ay' },
  { label_en: 'Azerbaijani', label: 'Azerbaijani', key: 'az' },
  { label_en: 'Bambara', label: 'Bambara', key: 'bm' },
  { label_en: 'Bashkir', label: 'Bashkir', key: 'ba' },
  { label_en: 'Basque', label: 'Basque', key: 'eu' },
  { label_en: 'Belarusian', label: 'Belarusian', key: 'be' },
  { label_en: 'Bengali (Bangla)', label: 'Bengali (Bangla)', key: 'bn' },
  { label_en: 'Bihari', label: 'Bihari', key: 'bh' },
  { label_en: 'Bislama', label: 'Bislama', key: 'bi' },
  { label_en: 'Bosnian', label: 'Bosnian', key: 'bs' },
  { label_en: 'Breton', label: 'Breton', key: 'br' },
  { label_en: 'Bulgarian', label: 'Bulgarian', key: 'bg' },
  { label_en: 'Burmese', label: 'Burmese', key: 'my' },
  { label_en: 'Catalan', label: 'Catalan', key: 'ca' },
  { label_en: 'Chamorro', label: 'Chamorro', key: 'ch' },
  { label_en: 'Chechen', label: 'Chechen', key: 'ce' },
  { label_en: 'Chichewa, Chewa, Nyanja', label: 'Chichewa, Chewa, Nyanja', key: 'ny' },
  { label_en: 'Chinese', label: 'Chinese', key: 'zh' },
  { label_en: 'Chinese (Simplified)', label: 'Chinese (Simplified)', key: 'zh-Hans' },
  { label_en: 'Chinese (Traditional)', label: 'Chinese (Traditional)', key: 'zh-Hant' },
  { label_en: 'Chuvash', label: 'Chuvash', key: 'cv' },
  { label_en: 'Cornish', label: 'Cornish', key: 'kw' },
  { label_en: 'Corsican', label: 'Corsican', key: 'co' },
  { label_en: 'Cree', label: 'Cree', key: 'cr' },
  { label_en: 'Croatian', label: 'Croatian', key: 'hr' },
  { label_en: 'Czech', label: 'Czech', key: 'cs' },
  { label_en: 'Danish', label: 'Danish', key: 'da' },
  {
    label_en: 'Divehi, Dhivehi, Maldivian',
    label: 'Divehi, Dhivehi, Maldivian',
    key: 'dv',
    rtl: true,
  },
  { label_en: 'Dutch', label: 'Dutch', key: 'nl' },
  { label_en: 'Dzongkha', label: 'Dzongkha', key: 'dz' },
  { label_en: 'English', label: 'English', key: 'en' },
  { label_en: 'Esperanto', label: 'Esperanto', key: 'eo' },
  { label_en: 'Estonian', label: 'Estonian', key: 'et' },
  { label_en: 'Ewe', label: 'Ewe', key: 'ee' },
  { label_en: 'Faroese', label: 'Faroese', key: 'fo' },
  { label_en: 'Fijian', label: 'Fijian', key: 'fj' },
  { label_en: 'Finnish', label: 'Finnish', key: 'fi' },
  { label_en: 'French', label: 'French', key: 'fr' },
  { label_en: 'Fula, Fulah, Pulaar, Pular', label: 'Fula, Fulah, Pulaar, Pular', key: 'ff' },
  { label_en: 'Galician', label: 'Galician', key: 'gl' },
  { label_en: 'Gaelic Scottish', label: 'Gaelic Scottish', key: 'gd' },
  { label_en: 'Gaelic (Manx)', label: 'Gaelic (Manx)', key: 'gv' },
  { label_en: 'Georgian', label: 'Georgian', key: 'ka' },
  { label_en: 'German', label: 'German', key: 'de' },
  { label_en: 'Greek', label: 'Greek', key: 'el' },
  { label_en: 'Guarani', label: 'Guarani', key: 'gn' },
  { label_en: 'Gujarati', label: 'Gujarati', key: 'gu' },
  { label_en: 'Haitian Creole', label: 'Haitian Creole', key: 'ht' },
  { label_en: 'Hausa', label: 'Hausa', key: 'ha', rtl: true },
  { label_en: 'Hebrew', label: 'Hebrew', key: 'he', rtl: true },
  { label_en: 'Herero', label: 'Herero', key: 'hz' },
  { label_en: 'Hindi', label: 'Hindi', key: 'hi' },
  { label_en: 'Hiri Motu', label: 'Hiri Motu', key: 'ho' },
  { label_en: 'Hungarian', label: 'Hungarian', key: 'hu' },
  { label_en: 'Icelandic', label: 'Icelandic', key: 'is' },
  { label_en: 'Ido', label: 'Ido', key: 'io' },
  { label_en: 'Igbo', label: 'Igbo', key: 'ig' },
  { label_en: 'Indonesian', label: 'Indonesian', key: 'in' },
  { label_en: 'Interlingua', label: 'Interlingua', key: 'ia' },
  { label_en: 'Interlingue', label: 'Interlingue', key: 'ie' },
  { label_en: 'Inuktitut', label: 'Inuktitut', key: 'iu' },
  { label_en: 'Inupiak', label: 'Inupiak', key: 'ik' },
  { label_en: 'Irish', label: 'Irish', key: 'ga' },
  { label_en: 'Italian', label: 'Italian', key: 'it' },
  { label_en: 'Japanese', label: 'Japanese', key: 'ja' },
  { label_en: 'Javanese', label: 'Javanese', key: 'jv' },
  { label_en: 'Kalaallisut, Greenlandic', label: 'Kalaallisut, Greenlandic', key: 'kl' },
  { label_en: 'Kannada', label: 'Kannada', key: 'kn' },
  { label_en: 'Kanuri', label: 'Kanuri', key: 'kr' },
  { label_en: 'Kashmiri', label: 'Kashmiri', key: 'ks', rtl: true },
  { label_en: 'Kazakh', label: 'Kazakh', key: 'kk' },
  { label_en: 'Khmer', label: 'Khmer', key: 'km' },
  { label_en: 'Kikuyu', label: 'Kikuyu', key: 'ki' },
  { label_en: 'Kinyarwanda (Rwanda)', label: 'Kinyarwanda (Rwanda)', key: 'rw' },
  { label_en: 'Kirundi', label: 'Kirundi', key: 'rn' },
  { label_en: 'Kyrgyz', label: 'Kyrgyz', key: 'ky' },
  { label_en: 'Komi', label: 'Komi', key: 'kv' },
  { label_en: 'Kongo', label: 'Kongo', key: 'kg' },
  { label_en: 'Korean', label: 'Korean', key: 'ko' },
  { label_en: 'Kurdish', label: 'Kurdish', key: 'ku', rtl: true },
  { label_en: 'Kwanyama', label: 'Kwanyama', key: 'kj' },
  { label_en: 'Lao', label: 'Lao', key: 'lo' },
  { label_en: 'Latin', label: 'Latin', key: 'la' },
  { label_en: 'Latvian (Lettish)', label: 'Latvian (Lettish)', key: 'lv' },
  { label_en: 'Limburgish (Limburger)', label: 'Limburgish (Limburger)', key: 'li' },
  { label_en: 'Lingala', label: 'Lingala', key: 'ln' },
  { label_en: 'Lithuanian', label: 'Lithuanian', key: 'lt' },
  { label_en: 'Luga-Katanga', label: 'Luga-Katanga', key: 'lu' },
  { label_en: 'Luganda, Ganda', label: 'Luganda, Ganda', key: 'lg' },
  { label_en: 'Luxembourgish', label: 'Luxembourgish', key: 'lb' },
  { label_en: 'Macedonian', label: 'Macedonian', key: 'mk' },
  { label_en: 'Malagasy', label: 'Malagasy', key: 'mg' },
  { label_en: 'Malay', label: 'Malay', key: 'ms' },
  { label_en: 'Malayalam', label: 'Malayalam', key: 'ml' },
  { label_en: 'Maltese', label: 'Maltese', key: 'mt' },
  { label_en: 'Maori', label: 'Maori', key: 'mi' },
  { label_en: 'Marathi', label: 'Marathi', key: 'mr' },
  { label_en: 'Marshallese', label: 'Marshallese', key: 'mh' },
  { label_en: 'Moldavian', label: 'Moldavian', key: 'mo' },
  { label_en: 'Mongolian', label: 'Mongolian', key: 'mn' },
  { label_en: 'Nauru', label: 'Nauru', key: 'na' },
  { label_en: 'Navajo', label: 'Navajo', key: 'nv' },
  { label_en: 'Ndonga', label: 'Ndonga', key: 'ng' },
  { label_en: 'Northern Ndebele', label: 'Northern Ndebele', key: 'nd' },
  { label_en: 'Nepali', label: 'Nepali', key: 'ne' },
  { label_en: 'Norwegian', label: 'Norwegian', key: 'no' },
  { label_en: 'Norwegian bokmål', label: 'Norwegian bokmål', key: 'nb' },
  { label_en: 'Norwegian nynorsk', label: 'Norwegian nynorsk', key: 'nn' },
  { label_en: 'Occitan', label: 'Occitan', key: 'oc' },
  { label_en: 'Ojibwe', label: 'Ojibwe', key: 'oj' },
  {
    label_en: 'Old Church Slavonic, Old Bulgarian',
    label: 'Old Church Slavonic, Old Bulgarian',
    key: 'cu',
  },
  { label_en: 'Oriya', label: 'Oriya', key: 'or' },
  { label_en: 'Oromo (Afaan Oromo)', label: 'Oromo (Afaan Oromo)', key: 'om' },
  { label_en: 'Ossetian', label: 'Ossetian', key: 'os' },
  { label_en: 'Pāli', label: 'Pāli', key: 'pi' },
  { label_en: 'Pashto, Pushto', label: 'Pashto, Pushto', key: 'ps', rtl: true },
  { label_en: 'Persian (Farsi)', label: 'Persian (Farsi)', key: 'fa', rtl: true },
  { label_en: 'Polish', label: 'Polish', key: 'pl' },
  { label_en: 'Portuguese', label: 'Portuguese', key: 'pt' },
  { label_en: 'Punjabi (Eastern)', label: 'Punjabi (Eastern)', key: 'pa' },
  { label_en: 'Quechua', label: 'Quechua', key: 'qu' },
  { label_en: 'Romansh', label: 'Romansh', key: 'rm' },
  { label_en: 'Romanian', label: 'Romanian', key: 'ro' },
  { label_en: 'Russian', label: 'Russian', key: 'ru' },
  { label_en: 'Sami', label: 'Sami', key: 'se' },
  { label_en: 'Samoan', label: 'Samoan', key: 'sm' },
  { label_en: 'Sango', label: 'Sango', key: 'sg' },
  { label_en: 'Sanskrit', label: 'Sanskrit', key: 'sa' },
  { label_en: 'Serbian', label: 'Serbian', key: 'sr' },
  { label_en: 'Serbo-Croatian', label: 'Serbo-Croatian', key: 'sh' },
  { label_en: 'Sesotho', label: 'Sesotho', key: 'st' },
  { label_en: 'Setswana', label: 'Setswana', key: 'tn' },
  { label_en: 'Shona', label: 'Shona', key: 'sn' },
  { label_en: 'Sichuan Yi, Nuosu', label: 'Sichuan Yi, Nuosu', key: 'ii' },
  { label_en: 'Sindhi', label: 'Sindhi', key: 'sd' },
  { label_en: 'Sinhalese', label: 'Sinhalese', key: 'si' },
  { label_en: 'Siswati, Swati', label: 'Siswati, Swati', key: 'ss' },
  { label_en: 'Slovak', label: 'Slovak', key: 'sk' },
  { label_en: 'Slovenian', label: 'Slovenian', key: 'sl' },
  { label_en: 'Somali', label: 'Somali', key: 'so' },
  { label_en: 'Southern Ndebele', label: 'Southern Ndebele', key: 'nr' },
  { label_en: 'Spanish', label: 'Spanish', key: 'es' },
  { label_en: 'Sundanese', label: 'Sundanese', key: 'su' },
  { label_en: 'Swahili (Kiswahili)', label: 'Swahili (Kiswahili)', key: 'sw' },
  { label_en: 'Swedish', label: 'Swedish', key: 'sv' },
  { label_en: 'Tagalog', label: 'Tagalog', key: 'tl' },
  { label_en: 'Tahitian', label: 'Tahitian', key: 'ty' },
  { label_en: 'Tajik', label: 'Tajik', key: 'tg' },
  { label_en: 'Tamil', label: 'Tamil', key: 'ta' },
  { label_en: 'Tatar', label: 'Tatar', key: 'tt' },
  { label_en: 'Telugu', label: 'Telugu', key: 'te' },
  { label_en: 'Thai', label: 'Thai', key: 'th' },
  { label_en: 'Tibetan', label: 'Tibetan', key: 'bo' },
  { label_en: 'Tigrinya', label: 'Tigrinya', key: 'ti' },
  { label_en: 'Tonga', label: 'Tonga', key: 'to' },
  { label_en: 'Tsonga', label: 'Tsonga', key: 'ts' },
  { label_en: 'Turkish', label: 'Turkish', key: 'tr' },
  { label_en: 'Turkmen', label: 'Turkmen', key: 'tk' },
  { label_en: 'Twi', label: 'Twi', key: 'tw' },
  { label_en: 'Uyghur', label: 'Uyghur', key: 'ug' },
  { label_en: 'Ukrainian', label: 'Ukrainian', key: 'uk' },
  { label_en: 'Urdu', label: 'Urdu', key: 'ur', rtl: true },
  { label_en: 'Uzbek', label: 'Uzbek', key: 'uz' },
  { label_en: 'Venda', label: 'Venda', key: 've' },
  { label_en: 'Vietnamese', label: 'Vietnamese', key: 'vi' },
  { label_en: 'Volapük', label: 'Volapük', key: 'vo' },
  { label_en: 'Wallon', label: 'Wallon', key: 'wa' },
  { label_en: 'Welsh', label: 'Welsh', key: 'cy' },
  { label_en: 'Wolof', label: 'Wolof', key: 'wo' },
  { label_en: 'Western Frisian', label: 'Western Frisian', key: 'fy' },
  { label_en: 'Xhosa', label: 'Xhosa', key: 'xh' },
  { label_en: 'Yiddish', label: 'Yiddish', key: 'yi', rtl: true },
  { label_en: 'Yoruba', label: 'Yoruba', key: 'yo' },
  { label_en: 'Zhuang, Chuang', label: 'Zhuang, Chuang', key: 'za' },
  { label_en: 'Zulu', label: 'Zulu', key: 'zu' },
];

const language = (key: string, purpose: keyof typeof elasticLanguages[number] = 'elastic') => {
  const defaultValue = purpose !== 'ISO639_1' ? 'other' : null;
  return elasticLanguages[key] ? elasticLanguages[key][purpose] : defaultValue;
};

export { elasticLanguages as languages, allLanguages, language };
