// eslint-disable-next-line no-restricted-imports
import { readdir, readFile, writeFile } from 'fs/promises';
import path from 'path';
import { ListenerManifestError } from './ListenerManifestError.js';

type ModuleManifest = {
  /** Directory scanned for listeners, relative to the repository root. */
  root: string;
  /** Where the module's manifest is written, relative to the repository root. */
  output: string;
};

/** Formats a generated file's source, given the path it is written to. */
type SourceFormatter = (source: string, output: string) => Promise<string>;

type Declaration = { name: string; file: string };

type ListenerEntry = { listener: Declaration; factory: Declaration };

const LISTENER = /class (\w+) extends Listener</g;
const HEADER =
  '// Generated by `yarn generate-listeners` (scripts/scripts.v2/ListenerManifestGenerator.ts).\n' +
  '// Do not edit: add a listener and its `<Listener>Factory`, then regenerate.\n';

/**
 * Writes, per module, the list of its V2 listeners paired with their factories, so a process can
 * register every listener without relying on what it happens to import. Reads source text only.
 */
class ListenerManifestGenerator {
  constructor(
    private repoRoot: string,
    private modules: ModuleManifest[],
    private format: SourceFormatter
  ) {}

  /** Each manifest's path, relative to the repository root, and its content. */
  async generate(): Promise<Map<string, string>> {
    const entriesByModule = await Promise.all(
      this.modules.map(async module => ({ module, entries: await this.entriesOf(module) }))
    );
    ListenerManifestGenerator.assertUniqueNames(entriesByModule.flatMap(({ entries }) => entries));

    const manifests = new Map<string, string>();
    await Promise.all(
      entriesByModule.map(async ({ module, entries }) => {
        manifests.set(module.output, await this.render(module, entries));
      })
    );
    return manifests;
  }

  async write(): Promise<void> {
    const manifests = await this.generate();
    await Promise.all(
      [...manifests].map(async ([output, content]) =>
        writeFile(path.join(this.repoRoot, output), content)
      )
    );
  }

  /** The manifests whose file is missing or differs from what would be generated. */
  async stale(): Promise<string[]> {
    const manifests = await this.generate();
    const stale = await Promise.all(
      [...manifests].map(async ([output, content]) =>
        (await this.readIfExists(output)) === content ? undefined : output
      )
    );
    return stale.filter((output): output is string => output !== undefined).sort();
  }

  private async entriesOf(module: ModuleManifest): Promise<ListenerEntry[]> {
    const sources = await this.sourcesOf(module.root);
    const listeners = sources.flatMap(({ file, content }) =>
      [...content.matchAll(LISTENER)].map(([, name]) => ({ name, file }))
    );

    return listeners
      .map(listener => ({
        listener,
        factory: ListenerManifestGenerator.factoryOf(listener, sources),
      }))
      .sort((a, b) => a.listener.name.localeCompare(b.listener.name));
  }

  private static factoryOf(
    listener: Declaration,
    sources: { file: string; content: string }[]
  ): Declaration {
    const name = `${listener.name}Factory`;
    const declaration = new RegExp(`class ${name}\\b[^]*?static default\\(`);
    const source = sources.find(({ content }) => declaration.test(content));
    if (!source) {
      throw new ListenerManifestError(`${listener.name} (${listener.file}) has no ${name}`);
    }
    return { name, file: source.file };
  }

  private static assertUniqueNames(entries: ListenerEntry[]) {
    const seen = new Map<string, string>();
    entries.forEach(({ listener }) => {
      const other = seen.get(listener.name);
      if (other) {
        throw new ListenerManifestError(
          `${listener.name} is declared twice: ${other} and ${listener.file}`
        );
      }
      seen.set(listener.name, listener.file);
    });
  }

  private async sourcesOf(root: string): Promise<{ file: string; content: string }[]> {
    const entries = await readdir(path.join(this.repoRoot, root), {
      recursive: true,
      withFileTypes: true,
    });
    const files = entries
      .filter(entry => entry.isFile() && ListenerManifestGenerator.isScanned(entry.name))
      .map(entry => path.relative(this.repoRoot, path.join(entry.parentPath, entry.name)))
      .filter(
        file => !file.split(path.sep).some(part => part === 'specs' || part === 'node_modules')
      )
      .sort();

    return Promise.all(
      files.map(async file => ({
        file,
        content: await readFile(path.join(this.repoRoot, file), 'utf8'),
      }))
    );
  }

  private static isScanned(filename: string) {
    return (
      filename.endsWith('.ts') && !filename.endsWith('.generated.ts') && !filename.endsWith('.d.ts')
    );
  }

  private async render(module: ModuleManifest, entries: ListenerEntry[]): Promise<string> {
    const importOf = ({ name, file }: Declaration) => {
      const relative = path
        .relative(path.dirname(module.output), file)
        .replace(/\.ts$/, '.js')
        .split(path.sep)
        .join('/');
      return `import { ${name} } from '${relative.startsWith('.') ? relative : `./${relative}`}';`;
    };

    const source = [
      HEADER,
      "import type { ListenerManifest } from '#api/core/libs/eventEmitter/ListenerManifest.js';",
      ...entries.flatMap(({ listener, factory }) => [importOf(listener), importOf(factory)]),
      '',
      'const listeners: ListenerManifest = [',
      ...entries.map(
        ({ listener, factory }) =>
          `{ listener: ${listener.name}, factory: () => ${factory.name}.default() },`
      ),
      '];',
      '',
      'export { listeners };',
      '',
    ].join('\n');

    return this.format(source, module.output);
  }

  private async readIfExists(output: string) {
    try {
      return await readFile(path.join(this.repoRoot, output), 'utf8');
    } catch {
      return undefined;
    }
  }
}

export { ListenerManifestGenerator };
export type { ModuleManifest, SourceFormatter };
