"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.SELECT_SNIPPET = exports.DEACTIVATE_REFERENCE = exports.ACTIVE_REFERENCE = exports.HIGHLIGHT_REFERENCE = exports.RESET_REFERENCE_CREATION = exports.SELECT_TARGET_DOCUMENT = exports.CLOSE_PANEL = exports.SHOW_TAB = exports.TARGET_PDF_READY = exports.PDF_READY = exports.OPEN_PANEL = exports.GO_TO_ACTIVE = exports.LOAD_DEFAULT_VIEWER_MENU = exports.REMOVE_REFERENCE = exports.ADD_REFERENCE = exports.VIEWER_UPDATE_DOCUMENT = exports.UNSET_TARGET_SELECTION = exports.SET_TARGET_SELECTION = exports.UNSET_SELECTION = exports.SET_SELECTION = exports.RESET_DOCUMENT_VIEWER = exports.SET_TARGET_DOCUMENT = exports.SET_DOCUMENT = exports.VIEWER_SET_THESAURIS = exports.VIEWER_SET_TEMPLATES = exports.SET_REFERENCES = void 0;const SET_REFERENCES = 'SET_REFERENCES';exports.SET_REFERENCES = SET_REFERENCES;
const VIEWER_SET_TEMPLATES = 'VIEWER_SET_TEMPLATES';exports.VIEWER_SET_TEMPLATES = VIEWER_SET_TEMPLATES;
const VIEWER_SET_THESAURIS = 'VIEWER_SET_THESAURIS';exports.VIEWER_SET_THESAURIS = VIEWER_SET_THESAURIS;
const SET_DOCUMENT = 'SET_DOCUMENT';exports.SET_DOCUMENT = SET_DOCUMENT;
const SET_TARGET_DOCUMENT = 'SET_TARGET_DOCUMENT';exports.SET_TARGET_DOCUMENT = SET_TARGET_DOCUMENT;
const RESET_DOCUMENT_VIEWER = 'RESET_DOCUMENT_VIEWER';exports.RESET_DOCUMENT_VIEWER = RESET_DOCUMENT_VIEWER;

const SET_SELECTION = 'SET_SELECTION';exports.SET_SELECTION = SET_SELECTION;
const UNSET_SELECTION = 'UNSET_SELECTION';exports.UNSET_SELECTION = UNSET_SELECTION;
const SET_TARGET_SELECTION = 'SET_TARGET_SELECTION';exports.SET_TARGET_SELECTION = SET_TARGET_SELECTION;
const UNSET_TARGET_SELECTION = 'UNSET_TARGET_SELECTION';exports.UNSET_TARGET_SELECTION = UNSET_TARGET_SELECTION;
const VIEWER_UPDATE_DOCUMENT = 'VEWER_UPDATE_DOCUMENT';

//REFERENCES
exports.VIEWER_UPDATE_DOCUMENT = VIEWER_UPDATE_DOCUMENT;const ADD_REFERENCE = 'ADD_CREATED_REFERENCE';exports.ADD_REFERENCE = ADD_REFERENCE;
const REMOVE_REFERENCE = 'REMOVE_REFERENCE';

//MENU
exports.REMOVE_REFERENCE = REMOVE_REFERENCE;const LOAD_DEFAULT_VIEWER_MENU = 'LOAD_DEFAULT_VIEWER_MENU';

//UI
exports.LOAD_DEFAULT_VIEWER_MENU = LOAD_DEFAULT_VIEWER_MENU;const GO_TO_ACTIVE = 'GO_TO_ACTIVE';exports.GO_TO_ACTIVE = GO_TO_ACTIVE;
const OPEN_PANEL = 'OPEN_PANEL';exports.OPEN_PANEL = OPEN_PANEL;
const PDF_READY = 'PDF_READY';exports.PDF_READY = PDF_READY;
const TARGET_PDF_READY = 'TARGET_PDF_READY';exports.TARGET_PDF_READY = TARGET_PDF_READY;
const SHOW_TAB = 'SHOW_TAB';exports.SHOW_TAB = SHOW_TAB;
const CLOSE_PANEL = 'CLOSE_PANEL';exports.CLOSE_PANEL = CLOSE_PANEL;
const SELECT_TARGET_DOCUMENT = 'SELECT_TARGET_DOCUMENT';exports.SELECT_TARGET_DOCUMENT = SELECT_TARGET_DOCUMENT;
const RESET_REFERENCE_CREATION = 'RESET_REFERENCE_CREATION';exports.RESET_REFERENCE_CREATION = RESET_REFERENCE_CREATION;
const HIGHLIGHT_REFERENCE = 'HIGHLIGHT_REFERENCE';exports.HIGHLIGHT_REFERENCE = HIGHLIGHT_REFERENCE;
const ACTIVE_REFERENCE = 'ACTIVE_REFERENCE';exports.ACTIVE_REFERENCE = ACTIVE_REFERENCE;
const DEACTIVATE_REFERENCE = 'DEACTIVATE_REFERENCE';exports.DEACTIVATE_REFERENCE = DEACTIVATE_REFERENCE;
const SELECT_SNIPPET = 'SELECT_SNIPPET';exports.SELECT_SNIPPET = SELECT_SNIPPET;