export default {
  ara: 'arabic',
  arm: 'armenian',
  baq: 'basque',
  bul: 'bulgarian',
  cat: 'catalan',
  cjk: 'cjk',
  ces: 'czech',
  dan: 'danish',
  nld: 'dutch',
  eng: 'english',
  fin: 'finnish',
  fra: 'french',
  glg: 'galician',
  deu: 'german',
  ell: 'greek',
  hin: 'hindi',
  hun: 'hungarian',
  ind: 'indonesian',
  gle: 'irish',
  ita: 'italian',
  lav: 'latvian',
  lit: 'lithuanian',
  nob: 'norwegian',
  nno: 'norwegian',
  fas: 'persian',
  por: 'portuguese',
  ron: 'romanian',
  rus: 'russian',
  ckb: 'sorani', //central kurdish
  spa: 'spanish',
  swe: 'swedish',
  tur: 'turkish',
  tha: 'thai'
};
