const BasicData = [
  { title: 'Entity 2', created: 2, description: 'Short text' },
  {
    title: 'Entity 1',
    created: 1,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel efficitur quam. Donec feugiat at libero at rutrum.',
    children: [
      {
        title: 'Entity a',
        created: 4,
        description: 'Donec feugiat at libero at rutrum.',
      },
      {
        title: 'Entity b',
        created: 5,
        description: 'Phasellus vel efficitur quam.',
      },
    ],
  },
  {
    title: 'Entity 3',
    created: 3,
    description: 'Morbi congue et justo vitae congue. Vivamus porttitor et leo vitae efficitur',
  },
];

const LongData = [
  { title: 'Entity 5', created: 1, description: 'Aliquam erat volutpat' },
  { title: 'Entity 22', created: 2, description: 'Morbi leo risus' },
  { title: 'Entity 16', created: 3, description: 'Maecenas faucibus mollis' },
  { title: 'Entity 12', created: 4, description: 'Cras justo odio' },
  { title: 'Entity 25', created: 5, description: 'Nullam quis risus eget' },
  { title: 'Entity 33', created: 6, description: 'Vestibulum id ligula' },
  { title: 'Entity 8', created: 7, description: 'Curabitur blandit tempus' },
  { title: 'Entity 3', created: 8, description: 'Aenean lacinia bibendum' },
  { title: 'Entity 10', created: 9, description: 'Praesent commodo cursus' },
  { title: 'Entity 29', created: 10, description: 'Vivamus sagittis lacus' },
  { title: 'Entity 36', created: 11, description: 'Cum sociis natoque' },
  { title: 'Entity 17', created: 12, description: 'Penatibus et magnis' },
  { title: 'Entity 20', created: 13, description: 'Dis parturient montes' },
  { title: 'Entity 18', created: 14, description: 'Nascetur ridiculus mus' },
  { title: 'Entity 6', created: 15, description: 'Donec ullamcorper nulla' },
  { title: 'Entity 15', created: 16, description: 'Vestibulum ante ipsum' },
  { title: 'Entity 1', created: 17, description: 'Primis in faucibus' },
  { title: 'Entity 37', created: 18, description: 'Orci luctus et' },
  { title: 'Entity 4', created: 19, description: 'Ultrices posuere cubilia' },
  { title: 'Entity 24', created: 20, description: 'Curae; Nulla dapibus' },
  { title: 'Entity 14', created: 21, description: 'Justo eget nulla' },
  { title: 'Entity 28', created: 22, description: 'Vestibulum quis magna' },
  { title: 'Entity 7', created: 23, description: 'Integer posuere erat' },
  { title: 'Entity 9', created: 24, description: 'A convallis aenean' },
  { title: 'Entity 23', created: 25, description: 'Euismod sit amet' },
  { title: 'Entity 40', created: 26, description: 'Aenean eu leo' },
  { title: 'Entity 35', created: 27, description: 'Quam pellentesque nec' },
  { title: 'Entity 30', created: 28, description: 'Vestibulum sed nisi' },
  { title: 'Entity 21', created: 29, description: 'Fringilla commodo' },
  { title: 'Entity 2', created: 30, description: 'Cum sociis natoque' },
  { title: 'Entity 38', created: 31, description: 'Et magnis dis' },
  { title: 'Entity 34', created: 32, description: 'Parturient montes' },
  { title: 'Entity 13', created: 33, description: 'Nascetur ridiculus mus' },
  { title: 'Entity 27', created: 34, description: 'Nulla posuere sollicitudin' },
  { title: 'Entity 11', created: 35, description: 'Quisque velit nisi' },
  { title: 'Entity 39', created: 36, description: 'Sed convallis' },
  { title: 'Entity 19', created: 37, description: 'Lacus vel facilisis' },
  { title: 'Entity 31', created: 38, description: 'Nulla porta dolor' },
  { title: 'Entity 32', created: 39, description: 'Sed blandit libero' },
  { title: 'Entity 26', created: 40, description: 'Porttitor eget dolor' },
];

export { BasicData, LongData };
