// Generated by `yarn generate-listeners` (scripts/scripts.v2/ListenerManifestGenerator.ts).
// Do not edit: add a listener and its `<Listener>Factory`, then regenerate.

import type { ListenerManifest } from '#api/core/libs/eventEmitter/ListenerManifest.js';
import { CleanupOcrRecordsOnFilesDeleted } from './listeners/CleanupOcrRecordsOnFilesDeleted.js';
import { CleanupOcrRecordsOnFilesDeletedFactory } from './factories/CleanupOcrRecordsOnFilesDeletedFactory.js';

const listeners: ListenerManifest = [
  {
    listener: CleanupOcrRecordsOnFilesDeleted,
    factory: () => CleanupOcrRecordsOnFilesDeletedFactory.default(),
  },
];

export { listeners };
