"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.RESET_RELATION_TYPE = exports.SET_RELATION_TYPES = exports.RELATION_TYPE_DELETED = exports.EDIT_RELATION_TYPE = exports.RELATION_TYPE_SAVED = void 0; //DATA
const RELATION_TYPE_SAVED = 'RELATION_TYPE_SAVED';exports.RELATION_TYPE_SAVED = RELATION_TYPE_SAVED;
const EDIT_RELATION_TYPE = 'EDIT_RELATION_TYPE';exports.EDIT_RELATION_TYPE = EDIT_RELATION_TYPE;
const RELATION_TYPE_DELETED = 'RELATION_TYPE_DELETED';exports.RELATION_TYPE_DELETED = RELATION_TYPE_DELETED;
const SET_RELATION_TYPES = 'SET_RELATION_TYPES';exports.SET_RELATION_TYPES = SET_RELATION_TYPES;
const RESET_RELATION_TYPE = 'RESET_RELATION_TYPE';exports.RESET_RELATION_TYPE = RESET_RELATION_TYPE;