import { DBFixture } from 'api/utils/testing_db';
import { SuggestionState } from 'shared/types/suggestionSchema';

export const fixtures: DBFixture = {
  ixsuggestions: [
    {
      entityId: 'shared1',
      propertyName: 'title',
      entityTitle: 'Robin',
      suggestedValue: 'Red Robin',
      currentValue: 'Robin',
      segment: 'Red Robin, a variation on the traditional Robin persona.',
      language: 'en',
      state: SuggestionState.matching,
      creationDate: 5,
      page: 2,
    },
    {
      entityId: 'shared1',
      propertyName: 'title',
      entityTitle: 'Robin',
      suggestedValue: 'HCT-04-CR-SC-0074',
      currentValue: 'Red Robin',
      segment: 'Robin Rojo, una variante del Robin tradicional',
      language: 'es',
      state: SuggestionState.pending,
      creationDate: 5,
      page: 2,
    },
    {
      entityId: 'shared2',
      entityTitle: 'Batman',
      propertyName: 'super powers',
      suggestedValue: 'scientific knowledge',
      segment: 'he relies on his own scientific knowledge',
      language: 'en',
      state: SuggestionState.empty,
      creationDate: 1,
      page: 5,
    },
    {
      entityId: 'shared2',
      entityTitle: 'Batman',
      propertyName: 'super powers',
      suggestedValue: 'conocimiento científico',
      segment: 'el confía en su propio conocimiento científico',
      language: 'es',
      state: SuggestionState.empty,
      creationDate: 1,
      page: 5,
    },
    {
      entityId: 'shared3',
      propertyName: 'title',
      entityTitle: 'Alfred',
      suggestedValue: 'Alfred Pennyworth',
      currentValue: 'Alfred',
      segment: "Batman's butler, Alfred Pennyworth",
      language: 'en',
      state: SuggestionState.pending,
      creationDate: 4,
      page: 3,
    },
    {
      entityId: 'shared4',
      propertyName: 'title',
      entityTitle: 'Joker',
      suggestedValue: 'Joker',
      currentValue: 'Joker',
      segment: ' Joker is a homicidal psychopath',
      language: 'en',
      state: SuggestionState.matching,
      creationDate: 3,
      page: 1,
    },
    {
      entityId: 'shared5',
      propertyName: 'title',
      entityTitle: 'Poison Ivy',
      suggestedValue: 'Poison Ivy',
      segment: 'Poison Ivy is a fictional character appearing in comic books',
      language: 'en',
      state: SuggestionState.empty,
      creationDate: 6,
      page: 2,
    },
    {
      entityId: 'shared6',
      propertyName: 'title',
      entityTitle: 'The Penguin',
      suggestedValue: 'Penguin',
      currentValue: 'The Penguin',
      segment: 'The Penguin is a Gotham City mobster.',
      language: 'en',
      state: SuggestionState.matching,
      creationDate: 2,
      page: 12,
    },
  ],
};
