name: Build App

permissions:
  contents: write

on:
  pull_request:
    branches:
      - development
      - production
      - staging

jobs:
  build-app:
    runs-on: ubuntu-24.04
    steps:
      # Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.js Setup with Dependency Caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Cache node modules and Cypress
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Build the Application
      - name: Build production
        run: yarn production-build

      # Save Build Output
      - name: Upload built app artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ./dist
          compression-level: 9
          retention-days: 1
