name: Check Translations

on:
  workflow_call:

jobs:
  check_translations:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('patches/**') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: ~/.yarn/berry
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-
      - name: Enable Corepack
        run: corepack enable
      - name: install dependencies
        run: yarn install
      - run: yarn check-translations
