name: Component testing

on:
  push:
    branches:
      - development
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress-run:
    name: Component testing
    runs-on: ubuntu-24.04
    env:
      CYPRESS_RETRIES: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn install
      - name: Get Cypress version
        id: cypress-version
        run: |
          echo "version=$(yarn info cypress version --silent | head -n 1)" >> $GITHUB_OUTPUT
      - name: Get Cypress from cache
        id: cypress-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ steps.cypress-version.outputs.version }}
      - name: Install Cypress
        if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: npx cypress install
      - name: generate global css
        run: yarn tailwind
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          component: true
          config-file: cypress.config.ts
          headed: false
        timeout-minutes: 15
