name: E2E Pipeline

on:
  push:
    branches: [development]
  pull_request:
    branches: [development, staging, production]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  precheck:
    uses: ./.github/workflows/precheck.yml

  build:
    needs: precheck
    if: needs.precheck.outputs.should_run == 'true'
    uses: ./.github/workflows/ci_build.yml

  e2e_cypress:
    needs: [precheck, build]
    if: needs.precheck.outputs.should_run == 'true'
    uses: ./.github/workflows/ci_e2e_cypress.yml

  e2e_puppeteer:
    needs: [precheck, build]
    if: needs.precheck.outputs.should_run == 'true'
    uses: ./.github/workflows/ci_e2e_puppeteer.yml

  check_translations:
    needs: [precheck, build]
    if: needs.precheck.outputs.should_run == 'true'
    uses: ./.github/workflows/ci_check_translations.yml
