name: E2E Pipeline

on:
  push:
    branches: [development]
  pull_request:
    branches: [development, staging, production]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup_mongosh:
    uses: ./.github/workflows/ci_setup_mongosh.yml

  build:
    needs: setup_mongosh
    uses: ./.github/workflows/ci_build.yml

  e2e_cypress:
    needs: [setup_mongosh, build]
    uses: ./.github/workflows/ci_e2e_cypress.yml

  e2e_puppeteer:
    needs: [setup_mongosh, build]
    uses: ./.github/workflows/ci_e2e_puppeteer.yml

  check_translations:
    needs: [setup_mongosh, build]
    uses: ./.github/workflows/ci_check_translations.yml
