name: E2E Pipeline

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The sha to checkout'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/ci_build.yml

  e2e_cypress:
    needs: [build]
    uses: ./.github/workflows/ci_e2e_cypress.yml

  e2e_puppeteer:
    needs: [build]
    uses: ./.github/workflows/ci_e2e_puppeteer.yml

  check_translations:
    needs: [build]
    uses: ./.github/workflows/ci_check_translations.yml
