name: CI Pipeline

on:
  push:
    branches: [development]
  pull_request:
    branches: [development, staging, production]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/ci_build.yml

  e2e_cypress_base:
    needs: build
    uses: ./.github/workflows/ci_e2e_cypress_base.yml

  e2e_cypress_IX:
    needs: build
    uses: ./.github/workflows/ci_e2e_cypress_IX.yml

  e2e_cypress_pages:
    needs: build
    uses: ./.github/workflows/ci_e2e_cypress_pages.yml

  e2e_cypress_settings:
    needs: build
    uses: ./.github/workflows/ci_e2e_cypress_settings.yml

  e2e_puppeteer:
    needs: build
    uses: ./.github/workflows/ci_e2e_puppeteer.yml

  check_translations:
    needs: build
    uses: ./.github/workflows/ci_check_translations.yml
