name: check-types

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The sha to checkout'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  check-types:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.sha }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn install
      - run: yarn check-types
